### ISSUE TITLE
Components interface "Modal"

### ISSUE THREAD

**Issue by LorenaDeSouza** [Esri/geoportal-server#102]
Hello, 
need some help ... 
How to put a modal with DOJO in results.jsp file. 
Clicking the "Details" link, I want to display a modal. 
Libraries used in the geoportal has support for creating interface components? 

Thank you, 
Lorena

**Comment by mhogeweg** [comment]
hi, you will have to use some dojo to code this. as a start:

include this in your results.jsp in the script section right before the closing </script> tag around line 430:

```
// Modal details dialog
function modalDetails(rowIndex) {
    scShowDialog('dlgDetailsPopup', true);
    var metadataRecord = jsMetadata.records[rowIndex];
    var dj = dijit.byId('dlgDetailsPopup');
    
    dj.setAttribute("title","the title for result " + metadataRecord.uuid + " go here");
    dj.setAttribute("content","the details to show go here");

    return false;
}
```
then include this outputLink in results.jsp right below the existing <h:outputLink> with id="_lnkZoomTo":

```
<% // open modal dialog with details %>
<h:outputLink id="_lnkModalDetails" 
      value="javascript:void(0)"  rendered="true" styleClass="resultsLink"
      onclick="javascript:modalDetails(#{dTable.dataTable.rowIndex});return false">
    <h:outputText id="_txtModalDetails" value="Modal" />
</h:outputLink>
```

the outputLink results in the javascript to be called. this uses the existing function scShowDialog() to show/hide the dialog and then you can initialize the contents as needed to show the details of the selected result (rowIndex)
