### ISSUE TITLE
Geoportal's CSW query is not stable

### ISSUE THREAD

**Issue by Yuanjie0913** [Esri/geoportal-server#115]
The CSW query through one of our geoportal servers sometime fails and sometime works. Especially when we query the results starting from 201. One example csw URL looks like 
http://data.nodc.noaa.gov/geoportal/csw?service=CSW&version=2.0.2&request=GetRecords&TypeNames=gmd:MD_Metadata&ElementSetName=full&resultType=results&outputFormat=application/xml&maxRecords=100&startPosition=201&outputSchema=http://www.isotc211.org/2005/gmd&constraint=%3CFilter%20xmlns:ogc=%22http://www.opengis.net/ogc%22%20xmlns:gml=%22http://www.opengis.net/gml%22%20xmlns:apiso=%22http://www.opengis.net/cat/csw/apiso/1.0%22%3E%3Cogc:BBOX%3E%3CPropertyName%3Eapiso:BoundingBox%3C/PropertyName%3E%3Cgml:Envelope%3E%3Cgml:lowerCorner%3E-180%2045%3C/gml:lowerCorner%3E%3Cgml:upperCorner%3E180%2090%3C/gml:upperCorner%3E%3C/gml:Envelope%3E%3C/ogc:BBOX%3E%3C/Filter%3E
This one works from time to time. And if you update the startPosition to 301, it works all the time. 

Could this be a bug or just server issue? Did anybody experience similar things before?

Any advice is appreciated!

Thanks,
Li

**Comment by mhogeweg** [comment]
hi Li, do you see any issues reported in the log files? I've tried this same request on our sandbox and that responds without problems:
http://gptogc.esri.com/geoportal/csw?service=CSW&version=2.0.2&request=GetRecords&TypeNames=gmd:MD_Metadata&ElementSetName=full&resultType=results&outputFormat=application/xml&maxRecords=100&startPosition=201&outputSchema=http://www.isotc211.org/2005/gmd&constraint=%3CFilter%20xmlns:ogc=%22http://www.opengis.net/ogc%22%20xmlns:gml=%22http://www.opengis.net/gml%22%20xmlns:apiso=%22http://www.opengis.net/cat/csw/apiso/1.0%22%3E%3Cogc:BBOX%3E%3CPropertyName%3Eapiso:BoundingBox%3C/PropertyName%3E%3Cgml:Envelope%3E%3Cgml:lowerCorner%3E-180%2045%3C/gml:lowerCorner%3E%3Cgml:upperCorner%3E180%2090%3C/gml:upperCorner%3E%3C/gml:Envelope%3E%3C/ogc:BBOX%3E%3C/Filter%3E

**Comment by Yuanjie0913** [comment]
This was brought up by one of our data users. He has set up a program to run this request daily. And since he did not complain about it recently, we can consider the issue is no more.  
Thanks for checking it. :)
