### ISSUE TITLE
Whitespace in XML supported in Geoportal Stylesheets?

### ISSUE THREAD

**Issue by dwoollcombe** [Esri/geoportal-server#119]
Hi,

I am having trouble getting whitespace (ie newlines) to appear in Geoportal stylesheets.  I know they are there as the exported XML displays okay in the Description tab for ArcGIS for Desktop.

Does anybody have advice as to whether whitespace is support or how to enable their use in Geoportal stylesheets?

Thanks

Damian

**Comment by mhogeweg** [comment]
This is a common question on the XML forums, but something not completely solvable due to the XML specification itself. Please see: http://stackoverflow.com/questions/260436/preserving-attribute-whitespace
