### ISSUE TITLE
How to publish from ArcCatalog but force ArcGIS Metadata Schema?

### ISSUE THREAD

**Issue by rwmajor2** [Esri/geoportal-server#129]
I have a customer that has a vast Oracle Geodatabase of FeatureClasses (thousands) with rich Metadata collected in ArcGIS Desktop.  We are using Geoportal Server to provide a means to search and use this data.  We are publishing from ArcCatalog using the Publish Client.  This was originally set up with 1.2 but now trying to upgrade to 1.2.5 Geoportal Server.  The default install for the Publish Client reports an error:  "Unrecognized metadata schema".  I believe this is occurring because I have commented out all schemas in the schemas.xml except for esri-arcgis, esri-iso, and dc.  However, I don't want the  Publish Client automatically transforming this to ISO19115, which is tries to do by default for some reason.  The old Publish Client worked.

Please advise on how to set this up to work properly with the new Publish Client.

**Comment by mhogeweg** [comment]
I have a python script that could be used to publish metadata from desktop. this with an 'identity translator' could possibly solve the issue you describe here.
