### ISSUE TITLE
Customizing search result view - changing  the abstract

### ISSUE THREAD

**Issue by j0chen** [Esri/geoportal-server#132]
When you click on a single item in the search result you can see a short description.
I try to add some additional information to this area and need some help.

I found out that in gpt.search.profiles.CSW_2.0.2_OGCCORE_ESRI_GPT_GetRecords_Response.xslt you can define wich content is rendered to the abstract ( xsl:choose / xsl:otherwise / Records / xsl:for-each / Record / Abstract / xsl:value-of ).
I also also found out that the html code for the search result can be changed in WebContent/catalog/search/results.jsp and that the value of the element defined in CSW_2.0.2_OGCCORE_ESRI_GPT_GetRecords_Response.xslt is stored in the parameter 'abstract'.

What i need is to have another parameter i can use in results.jsp, i.e. 'abstract2' with the value from a different elment, possibly defined as a new element in CSW_2.0.2_OGCCORE_ESRI_GPT_GetRecords_Response.xslt i.e. Abstract2 / xsl:value-of.
What steps are in between defining such a new element Abstract2 and finaly using it as a parameter 'abstract2'?

**Comment by mhogeweg** [comment]
hi @j0chen, do you want to show a longer abstract? or possibly popuplate the abstract field with values from more than one XML element (in case one of the two is empty)?

In both cases you could just append the two values in the Abstract element.

I would not recommend adding a second abstract2 element as that will result in many code changes between the CSW response and the search results page.
