### ISSUE TITLE
CSW Client does not appear in 'Commands' Tab

### ISSUE THREAD

**Issue by trillevine** [Esri/geoportal-server#134]
Following installation of the CSW Client (version 1.2.5 installed for ArcGIS 10.2.2 with .NET 3.5.30729), the 'Geoportal' option in the Categories menu in the Commands dialog window does not appear.  Installing the Publish Client solves this issue, but the CWS icon still does not appear in the 'Commands' portion of the window.  Anyone else experience this and have a sollution?

**Comment by zguo** [comment]
not sure if it is related to the .net framework version, do you have a .Net 4 or 4.5 environment you can check within ArcMap to see if it only happens with .NET 3.5.30729?  I only have a .net framework 4.5.x, seems to be working for me.
