### ISSUE TITLE
useless lines in SearchXslProfile.java

### ISSUE THREAD

**Issue by gcampanile** [Esri/geoportal-server#135]
In version 1.2.5 in function SearchXslProfile.java lines 421-422:
```
      } else if (nodeName.equals("ModifiedDate")) {
        record.setTypes(nodeValue);
```
are useless (and wrong, the record.setType call is not correct) because the same test is at lines 401-402.
Gianni

**Comment by mhogeweg** [comment]
you are correct. did you fix this already? if so can you submit a pull request?
