### ISSUE TITLE
WAF scheduled syncronization not deleting records

### ISSUE THREAD

**Issue by dwoollcombe** [Esri/geoportal-server#136]
Hi,

I have an issue where we have registered a WAF as a resource in Geoportal and metadata is being successfully copied however metadata that is removed from the WAF does not get deleted from Geoportal when the scheduled synchronization runs (currently set to once an hour).

The deleted statements do get removed from Geoportal when I manually run a "Full Synchronization".

Is this as designed and is there a way to automatically perform a Full Synchronizations?

Thanks

Damian

**Comment by pandzel** [comment]
Make sure you have the following in gpt.xml. It will enforce every scheduled harvest to be a full harvest:
 
&lt;parameter key="webharvester.policy.class" value="com.esri.gpt.control.webharvest.engine.SimpleHarvestPolicy"/&gt;
&lt;parameter key="webharvester.policy.simple.frequency" value="1"/&gt;

**Comment by dwoollcombe** [comment]
You suggestion has worked.

Thanks

Damian
