### ISSUE TITLE
PublishClient desktop add-ins missing Classes

### ISSUE THREAD

**Issue by g3r4n** [Esri/geoportal-server#137]
I'm trying to compile the project but it's seems that the ESRITranslator and MDPublisher classes are gone in 10.3 ArcObject SDK. Are you confirming ?

**Comment by mhogeweg** [comment]
hi, there is a limitation in ArcGIS Desktop 10.3 that results in this. It will be addressed in 10.3.1. Meanwhile, see #139 for a possible python approach to publishing.
