### ISSUE TITLE
Add a 10.3 build of the Desktop Clients 

### ISSUE THREAD

**Issue by lpinner** [Esri/geoportal-server#139]
The [downloads page](https://github.com/Esri/geoportal-server/wiki/Geoportal-Server-Downloads) only lists a 10.2 build of  the v.1.2.5 Desktop Clients (CSW Client, Publish Client, and WMC Client).

Would you please consider building and distributing binaries of the Desktop Clients for ArcGIS 10.3?

**Comment by zguo** [comment]
Just put the CSW Search Client and WMC Client for 10.3 on the download page, the Publish Client is currently not available for 10.3 due to some software limitations.

**Comment by lpinner** [comment]
Awesome, thankyou!

**Comment by mhogeweg** [comment]
Note, if you need to publish metadata from ArcGIS Desktop 10.3 to a Geoportal Server, I have a python script that can do this. can even run as a GP service that is then triggered now and then.

**Comment by mhogeweg** [comment]
we have released 1.2.6 of Geoportal Server which includes the 10.3.1 builds of the desktop clients.
