### ISSUE TITLE
Multiplicity

### ISSUE THREAD

**Issue by DonnaMills** [Esri/geoportal-server#140]
Hi

I understand Geoportal will support multiplicity for elements in the metadata editor. I have read the following article https://github.com/Esri/geoportal-server/wiki/GXE-Concepts but wondered whether there is any further information on how to implement it e.g. a tutorial as I am having difficulties understanding which files I need to edit to implement multiplicity for a specific element.

Many thanks

Donna

**Comment by mhogeweg** [comment]
The GXE-concepts article actually includes all you need to nkow about multiplicity. Just like with XML, you specify the minimum and maximum occurrences required/allowed for an element using these attributes: 

```
g:minOccurs="0" g:maxOccurs="unbounded".
```

here:
* g:minOccurs="0" implies something is optional
* g:minOccurs="1" implies something is mandatory
* g:maxOccurs="1" no more than 1 occurrence allowed.
* g:maxOccurs="unbounded" implies unlimited repetition possible of the element.
