### ISSUE TITLE
Is it possible to embed the Search Widget in an Javascript app (instead of Flex)?

### ISSUE THREAD

**Issue by Alex9200** [Esri/geoportal-server#141]
Is is possible to embed the Search Widget in an Javascript app (instead of Flex)?

**Comment by mhogeweg** [comment]
hi, we are working on creating a search widget for the ArcGIS Web AppBuilder framework. if you're interested we can look at including an early work-in-progress version on github.

**Comment by Alex9200** [comment]
that would be great! I would love to take a look at if it is not too early. Thank you,
Alex

**Comment by mhogeweg** [comment]
I have posted an initial version in a feature branch: https://github.com/Esri/geoportal-server/tree/feat/webappbuilder/widgets/search/components/webappbuilder/widgets/GeoportalSearch
