### ISSUE TITLE
Clarification on using multiple schemas in schemas.xml

### ISSUE THREAD

**Issue by nuest** [Esri/geoportal-server#143]
In the file ``geoportal/src/gpt/metadata/schemas.xml`` there is a NOTE stating that only ISO (x)or INSPIRE "should" be activated, see https://github.com/Esri/geoportal-server/blob/master/geoportal/src/gpt/metadata/schemas.xml#L36

*Can you clarify what will or could happen if both are activated?*

some background: We had to switch this to INSPIRE to get the upload with the ArcCatalog publish client (using INSPIRE metadata format) to work. The error message before merely stated that the data could not be uploaded...

**Comment by gcampanile** [comment]
Hi nuest,
the Geoportal uses an "interrogation" clause to identify the schema of a Metadata record. This "interrogation" is nothing else than an XPath query to check for some unique characteristics of the record. For example the INSPIRE interrogation is:
```
	<interrogation count="count(/gmd:MD_Metadata/gmd:identificationInfo/gmd:MD_DataIdentification)"/>
```
but this is the same interrogation of iso, from which INSPIRE is derived. So if you activate both profiles, the GPT will choose the first one that matches (in the order listed in schemas.xml). In other words, if the INSPIRE profile is before the ISO one in schemas.xml, than there will be no way to load a pure ISO xml metadata record, and this is the reason for your errors.
The ideal solution would be to define an interrogation that doesn't math ISO records but this in theory is impossible. In pratice you could add for example the check for at least one keyword containing INSPIRE and for at least one MS_Contraints definition, both mandatory in INSPIRE and very improbable to find them in a simple ISO metadata.

**Comment by nuest** [comment]
Thanks - this helps my understanding a lot. Could you point me towards the relevant documentation of that? In any case, this issue can be closed from my perspective, unless you want to keep it open if you feel like there is documentation missing.

Again: Thanks!

**Comment by gcampanile** [comment]
Glad to be helpful.
The wiki pages on adding a custom metadata profile go into detail and cover all different aspects of these topics, but in any case I realise that it's not easy to cope with all details. Just a final comment: I really wich that next realease of GPT will have an upload function that let the user choose the metadata profile, overriding the default interrogation. That would be really a great help.

Gianni

**Comment by mhogeweg** [comment]
the core issue is that INSPIRE forgot to declare a formal metadata standard name and version for its profile of ISO. As a result there's no real way to distinguish the two, leading to the recommendation. if you have both active, then the geoportal will pick the first matching schema to validate your metadata. it may be ok, but you do risk validating plain ISO against INSPIRE rules.
