### ISSUE TITLE
in DCAT implementation allow mapping between value domains

### ISSUE THREAD

**Issue by mhogeweg** [Esri/geoportal-server#144]
The specific domains for several elements of [Project Open Data Metadata Schema v1.1](https://project-open-data.cio.gov/v1.1/schema/) differ from the typical domains for the corresponding metadata element in ISO or FGDC metadata. Geoportal Server could allow defining a mapping between the values found in the geospatial metadata to values to be used in [Project Open Data Metadata Schema v1.1](https://project-open-data.cio.gov/v1.1/schema/).

For example, FGDC CSDGM records with ```secclass``` values “Medium Confidentiality” and “No Confidentiality” are currently mapping to “non-public”.

A suggested approach is to include mapping in ```dcat-mappings.xml ``` that use a regex to find values in the source metadata and map those to a target value to be included in the output json file.

**Comment by pandzel** [comment]
dcat-mappings.xml allows to define domain values mappings. For each string field it is possible to include &lt;map from="" to=""/&gt; collection of nodes. Each "from" is a regular expression matching input value (coming from the index) and "to" is output value printed to the DCAT json. Also, "to" might have value of "*" to indicate to pass original input value right to the output. Example:

&lt;field name="accessLevel" index="accessLevel" required="true"&gt;
&nbsp;&nbsp;&nbsp;&lt;map from=".*restricted.*" to="restricted public"/&gt;
&nbsp;&nbsp;&nbsp;&lt;map from="Medium Confidentiality" to="restricted public"/&gt;
&nbsp;&nbsp;&nbsp;&lt;map from="No Confidentiality" to="restricted public"/&gt;
&nbsp;&nbsp;&nbsp;&lt;map from="private|confidential|secret" to="non-public"/&gt;
&nbsp;&nbsp;&nbsp;&lt;map from=".*" to="public"/&gt;
&lt;/field&gt;
