### ISSUE TITLE
in DCAT JSON the distributionURLs need a mediatype

### ISSUE THREAD

**Issue by mhogeweg** [Esri/geoportal-server#146]
there are several URLs in Project Open Data Metadata Schema v1.1 that require the inclusion of a mediatype. since the typical source geospatial metadata does not include this information, it needs to be inferred from the URL included in that source metadata. A possible approach is to use regex to match URL patterns and then map those to an output mediatype that is included in the output JSON.

**Comment by smrazgs** [comment]
There is a community activity to crowdsource a registry of values to use for these kinds of properties to foster interoperability. Perhaps you could add mediatype strings for specific resource types there?
https://github.com/OSGeo/Cat-Interop

**Comment by pandzel** [comment]
It is possible to define mapping between url pattern and desired MIME type as "mediaType" element. It works in a similar manner as domain values mapping, except it is done through &lt;media url="" mime=""/&gt; element. The mechanism is in place, the only missing part to to come up with a reasonable list of mappings. It is true for both "accessURL" and "downloadURL" which are part of "distribution" element in DCAT1.1, "url" is a regular expression pattern matching the input URL, and the "mime" is just plain MIME type (mediaType). See, example:

&lt;field name="downloadURL" index="dcat.downloadUrl" required="false"&gt;
&nbsp;&nbsp;&nbsp;&lt;media url=".+\\.pdf$" mime="application/pdf"/&gt;
&nbsp;&nbsp;&nbsp;&lt;media url=".+\\.kmz$" mime="application/vnd.google-earth.kmz"/&gt;
&nbsp;&nbsp;&nbsp;&lt;media url=".+\\.doc$" mime="application/vnd.ms-word.document.macroEnabled.12"/&gt;
&lt;/field&gt;

**Comment by smrazgs** [comment]
mime types work OK for stuff that people look at, but if you're trying to implement some kind of machine interoperability, just knowing that something is JSON, CSV, or XML doesn't really tell you all you need to know if you want it to work.

**Comment by mhogeweg** [comment]
yep, and with modern web services the response (which I think is what typically is defined with the mediatype) can be a variety of things. there were some discussions on this in [POD issue 272](https://github.com/project-open-data/project-open-data.github.io/issues/272), but I'm not sure if those were really completed.
