### ISSUE TITLE
why is webService still in the dcat-mappings.xml?

### ISSUE THREAD

**Issue by mhogeweg** [Esri/geoportal-server#147]
Although the webService element is no longer included in schema 1.1, it’s still in the dcat-mappings.xml file. why is that?

**Comment by pandzel** [comment]
"webService" element is being kept for backward compatibility with DCAT1.0 schema. Although, by default, Geoportal Server will produce DCAT1.1 response, it is still possibly to configure it (in-explicitly) to produce old version of DCAT. It has been documented in dcat-mappings.xml for clarification.
