### ISSUE TITLE
In the latest geoportal version the accessLevelComment or rights element no longer appears in the data.json output

### ISSUE THREAD

**Issue by mhogeweg** [Esri/geoportal-server#148]
In the latest geoportal version the accessLevelComment or rights element no longer appears in the data.json output.  This is a mandatory field for non-public records.

**Comment by pandzel** [comment]
This has been implemented. However, in DCAT1.1 "accessLevelComment" is now called "rights" and that's exactly how it appears on the DCAT json output.
