### ISSUE TITLE
in DCAT implementation allow mapping between periodicity values to ISO 8601 equivalents

### ISSUE THREAD

**Issue by mhogeweg** [Esri/geoportal-server#149]
Include in the  Project Open Data Metadata Schema v1.1 implementation the ability to derive ISO 8601 notations for accrualPeriodicity field based on regex mapping of values in source metadata.

**Comment by pandzel** [comment]
It has been implemented already through the domain mapping mechanism. Current dcat-mapping.xml contains example of the mapping. Fragment of it below:

&lt;field name="accrualPeriodicity" index="dcat.accrualPeriodicity"  required="false"&gt;
&nbsp;&nbsp;&nbsp;&lt;map from="Daily" to="R/P1D"/&gt;
&nbsp;&nbsp;&nbsp;&lt;map from="Monthly" to="R/P1M"/&gt;
&nbsp;&nbsp;&nbsp;&lt;map from="Weekly" to="R/P1W"/&gt;
&nbsp;&nbsp;&nbsp;...
&nbsp;&nbsp;&nbsp;&lt;map from="^R/P[^DWMYS]*[DWMYS]$" to="*"/&gt;
&nbsp;&nbsp;&nbsp;&lt;map from=".+" to="irregular"/&gt;
&lt;/field&gt;
