### ISSUE TITLE
Basic Search/Search Results

### ISSUE THREAD

**Issue by Alex9200** [Esri/geoportal-server#151]
Hi,
This might be something very basic. When I search the registered data on my site, it seems like I have to type the full title of the registered data. For instance, I have "LayerVisible" as registered. If I type "Lay" it will return nothing, now if I type "LayerVisible", it will return the layer of interest. How can I get the searches results to show without typing the full title? Here is the repository in GPT.XML:

<repository 
                key="local" 
                class="com.esri.gpt.catalog.search.SearchEngineLocal"
                labelResourceKey="catalog.search.searchSite.defaultsite"
                abstractResourceKey="catalog.search.searchSite.defaultsite.abstract"/>  

Thank you,
Alex

**Comment by mhogeweg** [comment]
hi Alex, Geoportal Server supports most of the [Apache Lucene search syntax](https://github.com/Esri/geoportal-server/wiki/Using-Lucene-Search-Text-Queries), which includes using wildcards. 

In your case, searching for Lay* should do the trick!

**Comment by Alex9200** [comment]
Thank you that is it! How come I dont have to add wildcards when searching ArcGIS.com for instance? If I enter "G" (without wildcard) I have about 4095 results with letter G showing.

**Comment by mhogeweg** [comment]
different use of Lucene. we could have implemented auto-wildcarding in Geoportal Server, but we wanted to stick close to the Lucene syntax itself.

**Comment by Alex9200** [comment]
Ok. Thank you for your explanation! I will check with co-workers if they 'd rather have auto-wildcarding or if Lucene wildcard "*"  is fine.

**Comment by mhogeweg** [comment]
sure. but think about the consequences also: geoportal's search can do multiple terms, groupings, term boosting, exact phrases, etc. auto-wildcard is not always a good option.
Take a look at the [details of lucene indexing](https://github.com/Esri/geoportal-server/wiki/Details-of-Lucene-Indexing-in-the-Geoportal).
