### ISSUE TITLE
"Add to map" link for webappbuilder app

### ISSUE THREAD

**Issue by Alex9200** [Esri/geoportal-server#153]
Hi, I used the GeoportalSearch widget for webappbuilder and I am very pleased with how it looks. I just have one last step now: How do I "hook"  the "Add to Map" to the webappbuilder application that I downloaded and deployed to my inetpub?
Thank you,
Alex

**Comment by mhogeweg** [comment]
hi Alex. thanks for the feedback. regarding the hook, this is one thing we haven't developed yet. for this we'll need to extend the widget to insert some behaviors into the Web AppBuilder framework to capture the additional parameters (like you see on flex or ArcGIS Online viewers) with map service URL or such. perhaps something we can collaborate on?

**Comment by Alex9200** [comment]
Sure, I would love to collaborate on this. Not too sure how much I can contribute as I am pretty new to the Geoportal Server application and webappbuilder. I am willing to try though. Thanks, Alex

**Comment by andzejhelcom** [comment]
Are there any results in this issue? We are starting a new project and I  wonder if it is possible to have Geoportal's Add to map functionality in Web AppBuilder. If this is not implemented, then what is the main obstacle here? This is one of the main issues in our project.

**Comment by mhogeweg** [comment]
you may be interested in our widgets for Web AppBuilder: https://github.com/Esri/geoportal-server/tree/develop/components/wab/GeoportalSearch
