### ISSUE TITLE
"Preview" tab Not showing Map Services

### ISSUE THREAD

**Issue by Alex9200** [Esri/geoportal-server#154]
Hi all,
I am trying to preview some REST resources (Map Service) and some are not display in the preview tab. It adds to the map correctly and work fine otherwise. Any advice or idea what it could be?
Thank you,
Alex

**Comment by mhogeweg** [comment]
can you try this in http://gptogc.esri.com ? or share the URL to the service here?

**Comment by Alex9200** [comment]
I am going to share my service. I am getting it uploaded to my test ext server. It seems like it works great  http://gptogc.esri.com.

**Comment by Alex9200** [comment]
http://134.186.111.22/arcgis/rest/services/Alex_Try/Test/MapServer. Here is my map service.

**Comment by Alex9200** [comment]
Is this map service working for you? It still does not work for me.

**Comment by rexneville** [comment]
Hi Alex, is your metadata publicly visible on http://gptogc.esri.com ? Can you post a link to the metadata or give us the title to search for? Does you map service have any visible scale constraints?Some of our map services have no data visible at the initial extent/zoom scale in the preview window. Because there is no base map in the preview window for ArcGIS REST services then the preview can be blank and the user sees no base map to help them zoom in.

**Comment by Alex9200** [comment]
I posted it to http://gptogc.esri.com. There is no scale constraints.  The title name of the map service is: Test_AG. I see a blank  preview widow when hit "preview". Not too sure why.

**Comment by mhogeweg** [comment]
I approved the entry and am able to see the service without problems in [the preview page](http://gptogc.esri.com/geoportal/catalog/search/resource/livedata-preview.page?uuid={53C6F277-6388-4CC4-A74B-B1CB616B5D43}&url=http%3A%2F%2F134.186.111.22%2Farcgis%2Frest%2Fservices%2FAlex_Try%2FTest%2FMapServer&resourceType=ags&info=%2Fgeoportal%2Frest%2Fdocument%3Ff%3Dhtml%26showRelativeUrl%3Dtrue%26id%3D%257B53C6F277-6388-4CC4-A74B-B1CB616B5D43%257D)

**Comment by Alex9200** [comment]
livedata-preview.page:41 Uncaught TypeError: Cannot read property 'defaults' of undefined
js.arcgis.com/3.13compact/init.js:104 Uncaught Error: declare gpt.LiveData: unknown base class. Did you use dojo.require to pull it in?
embed.jsp:32 Uncaught TypeError: Cannot read property 'defaults' of undefined
js.arcgis.com/3.13compact/init.js:104 Uncaught Error: declare gpt.LiveData: unknown base class. Did you use dojo.require to pull it in?
parser.js:22 dojo/parser::parse() error TypeError: Cannot read property '_noScript' of undefined

**Comment by Alex9200** [comment]
After looking at my console here is what I got.

**Comment by Alex9200** [comment]
It seems like  I could not see my map service  because I used javascript API 3.13 in jsapiUrl instead of http://serverapi.arcgisonline.com/jsapi/arcgis/?v=2.8
 <interactiveMap
        jsapiUrl="http://serverapi.arcgisonline.com/jsapi/arcgis/?v=2.8"

**Comment by mhogeweg** [comment]
that could explain it. Geoportal Server uses the 2.8 version. we are planning to upgrade, but since we have some extensions we need to do this carefully.
