### ISSUE TITLE
WebAppBuilder Geoportal Search Widget not working when deployed in my environment

### ISSUE THREAD

**Issue by Alex9200** [Esri/geoportal-server#155]
Hi,
The Geoportal Search Widget in WebAppBuilder looks great and works fantastically. When downloaded and set up in my environment it does not work. The data I am searching is within my domain so I am not too sure I need a proxy or not. Does it need a proxy?
Thank you,
Alex

**Comment by mhogeweg** [comment]
hi Alex, the proxy is typically needed if the webapp has a different URL from the geoportal servers and services you would access.

**Comment by Alex9200** [comment]
Thank you, I will install a proxy then.
