### ISSUE TITLE
ISO North American Profile validation

### ISSUE THREAD

**Issue by rexneville** [Esri/geoportal-server#156]
I support the GeoDiscover Alberta geoportal server. We are running server version 1.2.5 and planning to use ISO 19115 North American Profile metadata soon (to eventually replace to our existing FGDC metadata). I have enabled the nap-iso-19115-definition in schemas.xml, putting it before other ISO definitions, but so far I have been unable to find any metadata XML examples that pass validation. Does that definition in geoportal v1.2.5 match the latest North American Profile? Can anyone point me to an example of ISO NAP metadata that works with that definition? Thanks in advance.

**Comment by tondevoldr** [comment]
At Agriculture and Agri-food Canada we are using 1.2.4 with the "Harmonized" North American Profile of ISO 19115.  You can contact me at ryan.tondevold@agr.gc.ca if you would like to discuss further.

**Comment by rexneville** [comment]
Thanks Ryan I will do that.

**Comment by tchaddad** [comment]
I'm interested in the answer to this question as well (if you were able to resolve it?). We recently ran into Geoportal validation problems with metadata generated by the jNAP tool, and we are trying to figure out if the metadata was generated incorrectly, or if the validation is not quite correct on the Geoportal side.

**Comment by mhogeweg** [comment]
we would welcome specific configurations of the profiles through pull requests. with respect to valid metadata, Geoportal Server allows for 'form validation' (force someone to enter something when editing or upload), schema validation (if we can find an xsd for a schema, we'll use it), and schematron validation ('when it rains on monday, the purpose field is optional'-style validation).

**Comment by tchaddad** [comment]
thanks Marten, we are going to try the schematron path, and will report back with any successes...

**Comment by mhogeweg** [comment]
cool. please see the [Customize Metadata Validation](https://github.com/Esri/geoportal-server/wiki/Customize-Metadata-Validation) topic on the wiki for some info.
