### ISSUE TITLE
Locale string catalog.search.searchSite.defaultsite is not being applied

### ISSUE THREAD

**Issue by marcelsip** [Esri/geoportal-server#157]
With localized Geoportal Server, search page shows always the default language label for local repository ("This Site") - regardless the localized string catalog.search.searchSite.defaultsite set in gpt.properties for given locale.
![thissite](https://cloud.githubusercontent.com/assets/8748061/7344966/01c77298-ecd1-11e4-8264-117d8c3755da.PNG)

**Comment by pandzel** [comment]
It appears to be fixed.
