### ISSUE TITLE
Download Data

### ISSUE THREAD

**Issue by Alex9200** [Esri/geoportal-server#158]
Hi all!
The download tab is a key component for our Geoportal. From what I see the download tab uses a list of layers published to ArcGIS Server (independently from Geoportal). Is there a way to manage the Geoportal's "data to download" directly from our Geoportal?
Thank you,
Alex

**Comment by mhogeweg** [comment]
hi Alex, not easily. as you correctly concluded, the list of layers comes from the clip-zip-ship geoprocessing tool that is published to ArcGIS Server.

what you could do (if you're into writing python tools) is write a new geoprocessing tool that accepts the extent and such as inputs, as well as one or more layers from a remote map service/feature service together with the URL to that service. The GP tool would then send the request to the remote web service, get the subset data and then do some local processing to reproject and such. Not rocket science, but with different service types, not entirely trivial either.
