### ISSUE TITLE
Unable to connect to the host.

### ISSUE THREAD

**Issue by g3r4n** [Esri/geoportal-server#160]
I can't add ressource from my network.
log :
avr. 30, 2015 10:29:02 AM org.apache.commons.httpclient.auth.AuthChallengeProcessor selectAuthScheme
INFOS: ntlm authentication scheme selected
avr. 30, 2015 10:29:02 AM org.apache.commons.httpclient.HttpMethodDirector processWWWAuthChallenge
INFOS: No credentials available for NTLM <any realm>@XXXXXXXXXX:80

**Comment by mhogeweg** [comment]
was this resolved?

**Comment by g3r4n** [comment]
No bu i will reopen it with further information
