### ISSUE TITLE
Administrative Tab

### ISSUE THREAD

**Issue by srijanapanthee** [Esri/geoportal-server#161]
Hi I am trying to geoportal with tomcat 7. If I login in gptuser it shows me green Welcome but it does not show welcome gptuser and after login there is no administrator tab

**Comment by mhogeweg** [comment]
are you using the simpleadapter or ldapadapter for authentication?

**Comment by srijanapanthee** [comment]
I am using simpleadapter

**Comment by mhogeweg** [comment]
the point of that one is that it's simple.. so something is wrong. can you paste the adapter section of gpt.xml here?

**Comment by srijanapanthee** [comment]
<identity encKey="PtkESRI" realm="Geoportal">  
        
        <simpleAdapter>
            <account username="gptuser" password="gptuser" encrypted="false"/>
            <roles>
                <role key="gptRegisteredUser"/>
                <role key="gptPublisher"/>
                <role key="gptAdministrator"/>
            </roles>
        </simpleAdapter>
        <!--
      
        <ldapAdapter>
            <ldapConnectionProperties
                providerURL="ldap://ldap_host_name:ldap_port"
                initialContextFactoryName="com.sun.jndi.ldap.LdapCtxFactory"
                securityAuthentication="simple"
                securityProtocol="">
                <ldapServiceAccount
                    securityPrincipal="ldap_admin_user"
                    securityCredentials="ldap_admin_password"
                    encrypted="false"/>
            </ldapConnectionProperties>

**Comment by mhogeweg** [comment]
can you check that the entire ldapAdapter section is commented out properly? or just remove it?

**Comment by srijanapanthee** [comment]
I have deleted all the entire ldapAdapter section but when I login gptuser still it shows me green Welcome banner

**Comment by mhogeweg** [comment]
does your tomcat show errors in the logs? is your site public?

**Comment by srijanapanthee** [comment]
I am trying to run geoportal from my local host and tomcat log files does not shows any errors

**Comment by mhogeweg** [comment]
can you send the entire gpt.xml to mhogeweg@esri.com?

**Comment by srijanapanthee** [comment]
<?xml version="1.0" encoding="UTF-8"?>

<gptConfig version="1.2.5">

    <databaseReference name="gpt" jndiName="jdbc/gpt"/>

    
    <mail
        smtpHost="mail_server_smtp_host"
        smtpPort=""
        siteEmailAddress="portal_contact_email_address"

emailAddressRegexp="^[a-zA-Z0-9,!#\$%&amp;'\*\+/=\?\^_`\{\|}~-]+(\.[a-zA-Z0-9,!#\$%&amp;'\*\+/=\?\^_`\{\|}~-]+)*@[a-zA-Z0-9-]+(\.[a-zA-Z0-9-]+)*$">
        <smtpAuth
            username=""
            password=""
            encrypted="false"/>
    </mail>


   

    <interactiveMap
        jsapiUrl="http://serverapi.arcgisonline.com/jsapi/arcgis/?v=2.5"
        mapServiceUrl="
http://server.arcgisonline.com/ArcGIS/rest/services/ESRI_Imagery_World_2D/MapServer
"
        mapServiceType="dynamic"
        geometryServiceUrl="
http://sampleserver3.arcgisonline.com/ArcGIS/rest/services/Geometry/GeometryServer
"
        locatorUrl=""
        locatorSingleFieldParameter = "city"/>

    <catalog gptTablePrefix="GPT_">
    

    <lucene
        indexLocation="C:\lucene"
        writeLockTimeout="60000"
        useNativeFSLockFactory="true"

analyzerClassName="org.apache.lucene.analysis.standard.StandardAnalyzer">
    
    </lucene>

    
    <parameter key="lucene.alwaysStoreXmlInIndex" value="false"/>
    <parameter key="lucene.force.isPartOf" value=""/>
    <parameter key="lucene.useSingleSearcher" value="true"/>
    <parameter key="lucene.useSingleWriter" value="true"/>
    <parameter key="lucene.useLocalWriter" value="true"/>
    <parameter key="lucene.useRemoteWriter" value="false"/>
    <parameter key="lucene.remoteWriterUrl" value=""/>

    
    <parameter key="assertion.index.enabled" value="true"/>
    <parameter key="assertion.index.location" value="C:\lucene\assertion"/>
    <parameter key="assertion.index.allowNonLocalResourceIds"
value="false"/>
    <parameter key="assertion.rating.enabled" value="true"/>
    <parameter key="assertion.comment.enabled" value="true"/>
    <parameter key="assertion.comment.maxLength" value="2048"/>

    
    
    <mapViewer>
        <instance
            url="{contextPath}/viewer/index.jsp"
            className="com.esri.gpt.catalog.search.MapViewerFlex_2_4">
        <parameter key="width" value="1000"/>
        <?arameter key="height" value="700"/>
        <parameter key="regexCanConsumeUrl" value=""/>
        </instance>
    </mapViewer>

    

    

    <search
        searchTimeoutMillisecs="10000"
        distributedSearchTimeoutMillisecs="5000"
        distributedSearchMaxSelectedSites="5"
        searchResultsPerPage="10"
        searchResultsReviewsShown="only-reviewed"
        maxSavedSearches="10"
        allowExternalSiteSearch="true"
        allowTemporalSearch="true">
        
        <repositories>
            <repository
                key="local"
                class="com.esri.gpt.catalog.search.SearchEngineLocal"
                labelResourceKey="catalog.search.searchSite.defaultsite"

abstractResourceKey="catalog.search.searchSite.defaultsite.abstract"/>
            
            <repository key="^$"
                class="com.esri.gpt.catalog.search.SearchEngineLocal"
                labelResourceKey=""
                abstractResourceKey=""/>
            
            <repository key="arcgis.com"
                class="com.esri.gpt.catalog.search.SearchEngineRest"
                labelResourceKey="catalog.search.searchSite.agsonline"

abstractResourceKey="catalog.search.searchSite.agsonline.abstract">
                <parameter key="endPointSearchUrl"
                    value="
http://www.arcgis.com/sharing/search?q={searchTerms}&amp;start={startIndex}&amp;num={count}&amp;f=json"/>

                <parameter key="defaultParamValues"
                    value="q&#x2714;access:shared || access:public ||
access:private "/>
                <parameter key="profileId"
                    value="urn:esri:gpt:HTTP:JSON:ESRI:AGSONLINE" />
            </repository>
             <repository
                 key="dataGov"
                 class="com.esri.gpt.catalog.search.SearchEngineExternalCsw"
                 labelResourceKey="catalog.search.searchSite.dataGov"

 abstractResourceKey="catalog.search.searchSite.dataGov.abstract"
                >
                <parameter key="profileId"
 ?                  value="urn:ogc:CSW:2.0.2:HTTP:APISO:PYCSW" />
                <parameter key="url"
                    value="
http://catalog.data.gov/csw?service=CSW&amp;version=2.0.2&amp;request=GetCapabilities"
/>
            </repository>
            <repository
                 key="geodab"
                 class="com.esri.gpt.catalog.search.SearchEngineExternalCsw"
                 labelResourceKey="catalog.search.searchSite.geoDab"

 abstractResourceKey="catalog.search.searchSite.geoDab.abstract"
                >
                <parameter key="profileId"
                    value="urn:ogc:CSW:2.0.2:HTTP:APISO:GICAT" />
                <parameter key="url"
                    value="
http://production.geodab.eu/gi-cat-StP/services/cswiso?request=GetCapabilities&amp;service=CSW&amp;version=2.0.2"
/>
            </repository>
            
            <repository key="*"

 class="com.esri.gpt.catalog.search.SearchEngineExternalCsw"/>
        </repositories>

        
        <searchResultFormat>
            <format regexFormat="csv"
class="com.esri.gpt.control.georss.CsvWriter">
            </format>
            </searchResultFormat>
        </search>

        
        <metadataAccessPolicy type="unrestricted"/>

        

        <parameter key="sitemap.baseUrl" value=""/>
        <parameter key="sitemap.documentUrlPattern"
value="/sitemap/document/{0}?f=html"/>
        <parameter key="sitemap.documentUrl?attern.html"
value="/sitemap/document/{0}?f=html"/>
        <parameter key="sitemap.documentUrlPattern.htmlfragment"
value="/sitemap/document/{0}?f=htmlfragment"/>
        <parameter key="sitemap.documentUrlPattern.xml"
value="/sitemap/document/{0}?f=xml"/>
        <parameter key="sitemap.documentUrlPattern.kml"
value="/sitemap/document/{0}?f=kml"/>
        <parameter key="sitemap.urlsPerIndexFile" value="1000"/>
        <parameter key="sitemap.urlsPerSitemapFile" value="1000"/>
        <parameter key="sitemap.namespaceUri" value="
http://www.sitemaps.org/schemas/sitemap/0.9"/>
        <parameter key="sitemap.changefreq" value="weekly"/>
        <parameter key="sitemap.priority" value=""/>

        
        <parameter key="webharvester.active" value="true"/>
        <parameter key="webharvester.queueEnabled" value=""/>
        <parameter key="webharvester.poolsize" value=""/>
        <parameter key="webharvester.autoSelectFrequency" value=""/>
        <parameter key="webharvester.watchDogFrequency" value=""/>
        <parameter key="webharvester.baseContextPath" value=""/>
        <parameter key="webharvester.maxRepRecords" value="70"/>
        <parameter key="webharvester.maxRepErrors" value="7"/>
        <parameter key="webharvester.resource.autoApprove" value=""/>
        <parameter key="webharvester.updateindex" value="true"/>
        <parameter key="webharvester.cleanup" value="true"/>
        <parameter key="webharvester.policy.class"
value="com.esri.gpt.control.webharvest.engine.SimpleHarvestPolicy"/>
        <parameter key="webharvester.policy.simple.frequency" value="1"/>
        <parameter key="webharvester.agp2agp.maxItems" value="2000"/>

        
        <parameter key="catalog.enableEditForAllPubMethods" value="false"/>
        <parameter key="catalog.admin.allowApplyToAll" value="true"/>
        <parameter key="catalog.useCollections" value="false"/>
        <parameter key="database.isCaseSensitive" value="true"/>
        <parameter key="publicationRequest.autoApprove" value="false"/>
        <parameter key="spatialRelevance.ranking.maxDoc" value="1000000"/>
        <parameter key="rssProviderUrl" value=""/>
        <parameter key="reverseProxy.baseContextPath" value=""/>
        <parameter key="RestServlet.printXml.stripStyleSheets"
value="true"/>
        <parameter key="Administration.viewMetadata.stripStyleSheets"
value="true"/>
        <parameter key="httpClientRequest.connectionTimeout"
value="2[MINUTE]"/>
        <parameter key="httpClientRequest.responseTimeout"
value="2[MINUTE]"/>
        <parameter key="httpClient.alwaysClose" value="false"/>


    
        <parameter key="resourceLinkBuilder.preview.filter" value="^ftp://
.*|^ftps://.*|.*\.zip$|.*\.e00$|.*\.lpk$|.*\.pkinfo$|.*\.gz$|.*\.tgz$|.*\.tar$|.*\.rar$|.*\.shp$|.*\.dbf$|.*\.xls$|.*\.dwg$|.*\.dxf$|.*\.dgn$|.*\.mxd$|.*\.lyr$|.*\.nmf$|.*f=lyr.*|.*f=nmf.*|.*/globeserver.*|.*/gpserver.*|.*/geocodeserver.*|.*/geometryserver.*|.*/networkserver.*|.*/geodataserver.*|.*service=wfs.*|.*wfsserver.*|.*service=wcs.*|.*wcsserver.*|.*service=csw.*|.*cswserver.*|.*mobileserver.*|.*naserver.*"/>

        
        <parameter key="ldap.identity.manage.userRoleEnabled"
value="true"/>
        
        <parameter key="ldap.identity.restrictToConfiguredRoles"
value="true"/>
        
        <parameter key="ldap.identity.search.maxResults" value="1000"/>

        
        <parameter key="servicechecker.enabled" value="false"/>
        <parameter key="servicechecker.token" value=""/>
        <parameter key="servicechecker.checkUrl" value="
http://registry.fgdc.gov/statuschecker/api/v2/results"/>
        <parameter key="servicechecker.infoUrl" value="
http://registry.fgdc.gov/statuschecker/ServiceDetail.php"/>

        
        <parameter key="catalog.cart.enabled" value="false"/>
        <parameter key="catalog.cart.maxItems" value="100"/>
        <parameter key="catalog.cart.processor"
value="com.esri.gpt.control.cart.ZipXmls"/>


<parameter key="dcat.mappings" value="gpt/metadata/dcat-mappings.xml"/>
        
        <parameter key="dcat.cache.path" value=""/>
    </catalog>

    

    <downloadData
        taskUrl=""
        mapServiceUrl=""
        mapServiceType="">

        <features>
            <feature key="File Geodatabase - GDB - .gdb" alias="gdb"
resKey="catalog.download.feature.gdb"/>
            <feature key="Shapefile - SHP - .shp" alias="shp"
resKey="catalog.download.feature.shp"/>
            <feature key="Autodesk AutoCAD - ACAD - .dxf" alias="dxf"
resKey="catalog.download.feature.dxf"/>
            <feature key="Autodesk AutoCAD - ACAD - .dwg" alias="dwg"
 resKey="catalog.download.feature.dwg"/>
            <feature key="Bentley Microstation Design (V8) - DGN_V8 - .dgn"
alias="dgn"  resKey="catalog.download.feature.dgn"/>
        </features>

        <rasters>
            <raster key="ESRI GRID - GRID" alias="grd"
resKey="catalog.download.raster.grd"/>
            <raster key="File Geodatabase - GDB - .gdb" alias="gdb"
resKey="catalog.download.raster.gdb"/>
            <raster key="ERDAS IMAGINE - IMG - .img" alias="img"
 resKey="catalog.download.raster.img"/>
            <raster key="Tagged Image File Format - TIFF - .tif"
alias="tif"  resKey="catalog.download.raster.tif"/>
            <raster key="Graphic Interchange Format - GIF - .gif"
alias="gif"  resKey="catalog.download.raster.gif"/>
            <raster key="Joint Photographics Experts Group - JPEG - .jpg"
alias="jpg"  resKey="catalog.download.raster.jpg"/>
            <raster key="Joint Photographics Experts Group - JPEG 2000 -
.jp2" alias="jp2"  resKey="catalog.download.raster.jp2"/>
            <raster key="Bitmap - BMP - .bmp" alias="bmp"
 resKey="catalog.download.raster.bmp"/>
         ?  <raster key="Portable Network Graphics - PNG - .png"
alias="png"  resKey="catalog.download.raster.png"/>
        </rasters>

        
        
    </downloadData>

    
    <identity encKey="PtkESRI" realm="Geoportal">

        <simpleAdapter>
            <account username="gptuser" password="gptuser"
encrypted="false"/>
            <roles>
                <role key="gptRegisteredUser"/>
                <role key="gptPublisher"/>
                <role key="gptAdministrator"/>
            </roles>
        </simpleAdapter>
        
    </identity>

    
    <scheduler active="true" corePoolSize="0">
        
        <thread class="com.esri.gpt.catalog.context.CatalogSynchronizer"
at="01:00"/>

        
        

        
        <thread class="com.esri.gpt.control.georss.dcatcache.DcatCacheTask"
period='1[DAY]' delay="15[SECOND]"/>
    </scheduler>

    
    <protocols default="false">
      <protocol factoryClass="
com.esri.gpt.control.webharvest.pro?ocol.factories.ResourceProtocolFactory"

resourceKey="catalog.harvest.manage.edit.protocol.resource"/>
      <protocol
factoryClass="com.esri.gpt.control.webharvest.protocol.factories.ArcGISProtocolFactory"
                resourceKey="catalog.harvest.manage.edit.protocol.arcgis"/>
      <protocol
factoryClass="com.esri.gpt.control.webharvest.protocol.factories.ArcImsProtocolFactory"
                resourceKey="catalog.harvest.manage.edit.protocol.arcims"/>
      <protocol
factoryClass="com.esri.gpt.control.webharvest.protocol.factories.OaiProtocolFactory"
                resourceKey="catalog.harvest.manage.edit.protocol.oai"/>
      <protocol
factoryClass="com.esri.gpt.control.webharvest.protocol.factories.WafProtocolFactory"
                resourceKey="catalog.harvest.manage.edit.protocol.waf"/>
      <protocol
factoryClass="com.esri.gpt.control.webharvest.protocol.factories.CswProtocolFactory"
                resourceKey="catalog.harvest.manage.edit.protocol.csw"/>
      <protocol
factoryClass="com.esri.gpt.control.webharvest.protocol.factories.ThreddsProtocolFactory"
                resourceKey="catalog.harvest.manage.edit.protocol.thredds"/>
      <protocol
factoryClass="com.esri.gpt.control.webharvest.protocol.factories.AtomProtocolFactory"
                resourceKey="catalog.harvest.manage.edit.protocol.atom"/>




      <protocol
factoryClass="com.esri.gpt.control.webharvest.protocol.factories.DCATProtocolFactory"
               resourceKey="catalog.harvest.manage.edit.protocol.dcat"/>
    </protocols>

</gptConfig>

**Comment by mhogeweg** [comment]
hi, you had some invalid characters in the file. I recommend some form of XML validator to verify your edits. even opening in a browser and using the developer tools to see if there are errors will help. I edited the file (removed all the comments) and posted it as a gist: https://gist.github.com/mhogeweg/643855607852f3ef784c

I also configured the geoportal server to use ArcGIS Online's map viewer.

please try this file.

**Comment by srijanapanthee** [comment]
Thank you very much now I can run and see administrative tab and it shows welcome gptuser.

**Comment by mhogeweg** [comment]
enjoy!

**Comment by srijanapanthee** [comment]
Thanks

**Comment by srijanapanthee** [comment]
I closed computer and restart and login as a gptuser it gives me Unable to connect to LDAP. error. It was working before and I did not changed anything

**Comment by mhogeweg** [comment]
if you have geoportal.war in the webapps folder, tomcat may redeploy it after a reboot/restart of tomcat. to make sure your edits stick:
- stop tomcat
- remove the .war file from webapps
- keep the geoportal folder in webapps
- apply your changes to gpt.xml.
- restart tomcat

**Comment by srijanapanthee** [comment]
thanks

**Comment by srijanapanthee** [comment]
Thank you very much now I can upload files also.

**Comment by rizkitampan** [comment]
Hi I am trying to geoportal with tomcat 7. If I login in gptadmin it shows me Unable to connect to LDAP. what im trying to do is run geoportal in localhost and im still confused for ldap setting, can somebody teach me how to fix it?, any way i was installed apache directory DS and using mysql for my DB. my question : 
How to relate between this LDAP setting in geoportal especially in gpt.xml and geoportal.xml , mysql and apache DS, your help is needed
