### ISSUE TITLE
Metadata Editor in Portal for ArcGIS 10.3 & 10.3.1?

### ISSUE THREAD

**Issue by kerryrobinson** [Esri/geoportal-server#162]
Should there be any issues following the [instructions](../tree/develop/geoportal/etc/Metadata) to add the GXE Editor in Portal for ArcGIS version 10.3 or 10.3.1? Has this been tested?

**Comment by srijanapanthee** [comment]
Hi,

Thanks for your query. I am not tested yet. I will do this after sometime.
I have some due projects so I will be back after this.

Srijana

**Comment by mhogeweg** [comment]
hi Kerry, yes, this should work fine with 10.3 (tested) and 10.3.1 (about to test)

**Comment by kerryrobinson** [comment]
Thanks Marten!  Let us know how the 10.3.1 testing goes.

**Comment by mhogeweg** [comment]
hi Kerry, we have just released Geoportal Server 1.2.6 and this has the metadata editor verified with Portal for ArcGIS 10.3.1!

**Comment by kerryrobinson** [comment]
Thanks @mhogeweg!
