### ISSUE TITLE
Publish Client alternative for 10.3 and 10.3.1

### ISSUE THREAD

**Issue by ctoledo-img-com-br** [Esri/geoportal-server#163]
Hi folks,

When can we expect the Desktop Publish Client 10.3.1 to be released? Until then,  what is the 10.3 alternative?

Thanks,
Carlos.

**Comment by mhogeweg** [comment]
hi Carlos, we are looking to release geoportal server 1.2.6 within the next weeks. that release will also include updated desktop clients.
