### ISSUE TITLE
Question : Portal metadata and Geoportal Server

### ISSUE THREAD

**Issue by g3r4n** [Esri/geoportal-server#164]
How to use metadata of Portal in Geoportal Server ?

**Comment by g3r4n** [comment]
I've understand that it's just the metadata editor of Geoportal that we can use in Portal for ArcGIS. 
We can't use the metadata on Portal in Geoportal.

**Comment by mhogeweg** [comment]
if you want to harvest Portal for ArcGIS items into Geoportal Server, you can use the ArcGIS Portal ATOM feed and register those.

**Comment by g3r4n** [comment]
Thanks for the idea ! Can you give me a link of the documentation ?

**Comment by mhogeweg** [comment]
here you go: https://github.com/Esri/geoportal-server/wiki/How-to-Publish-Resources#atom

**Comment by g3r4n** [comment]
You can register Portal for ArcGIS items but you can't retrieve the metadata you create via editor. i would like to register metadata create frome GXE Editor in Portal for ArcGIS in Geoportal.
