### ISSUE TITLE
Publish Client logs

### ISSUE THREAD

**Issue by g3r4n** [Esri/geoportal-server#165]
I can't find the log of the Publish client in the folder i specified during the installation.
Where can i find the logs ?

**Comment by mhogeweg** [comment]
This would have been set during installation. The default location is: ```C:\ProgramData\ESRI\GeoportalPublishClient```.

**Comment by g3r4n** [comment]
Like i said there are nothing in the folder i specified during the installation...

**Comment by g3r4n** [comment]
![image](https://cloud.githubusercontent.com/assets/10941033/7706371/59b0ce66-fe4a-11e4-8b16-b5bd2d2b14ff.png)
![image](https://cloud.githubusercontent.com/assets/10941033/7706387/7b259c2a-fe4a-11e4-8693-a75bed18d7bb.png)

**Comment by mhogeweg** [comment]
check this documentation: https://github.com/Esri/geoportal-server/wiki/Logging#Enable_logging_for_the_Geoportal_Clients

**Comment by g3r4n** [comment]
here is the log :

************ Metadata Publishing started at   20/05/2015 15:16:18 ************
Publication Parameters 
============================================================
Metadata Server Url           : https://XXXXXXX.com/geoportal
Publish Metadata Service Name : GPT_Publish_Metadata
Selected Workspace Name       : C:\Users\EDESVAUX\Downloads\metadata (6).xml
Selected container category   : XML Document
============================================================

Where is the error ?
How to define log level ?

**Comment by mhogeweg** [comment]
hmmm, the error could happen at the Geoportal Server itself when it tries to validate the XML. does your Geoportal Server log (normally tomcat\logs\gpt... show errors related to publication?
