### ISSUE TITLE
WIth Portal 10.3.1 the sorters node has changed

### ISSUE THREAD

**Issue by fleray** [Esri/geoportal-server#174]
For the delpoyment on Portal for ArcGIS 10.3.1, the node "arcgisonline_sharing_dijit_Sorter_0" does no more exist and has been replaced by "sorters".

Add the paragraph : 
10.3.1 DEPLOYMENT:

1. Follow the 10.2 deployment steps above.

2. Open the file "federated-searches-json.js" that is within folder "custom". 

3. Remove the prefix "esri_" from the IDs, at lines 87 and 88.
 
var targetNode = dojo.byId("arcgisonline_sharing_dijit_SearchResultsSimple_0");
var targetHeaderNode = dojo.byId("resultsLabel");

Change :
var targetSortersNode = dojo.byId("arcgisonline_sharing_dijit_Sorter_0");
 by : 
var targetSortersNode = dojo.byId("sorters");

This is necessary because the the Portal for ArcGIS search.html page changed some IDs of HTML elements at 10.3.1.

**Comment by mhogeweg** [comment]
thanks for the write-up. I've added this to the readme file and also created a [wiki page](https://github.com/Esri/geoportal-server/wiki/Federated-Search-in-Portal-for-ArcGIS) for the whole topic.
