### ISSUE TITLE
SEVERE: Error parsing XSD, schema=gemini-iso-19119 xsdLocation=http://eden.ign.fr/xsd/isotc211/isofull/20090316/srv/srv.xsd

### ISSUE THREAD

**Issue by pbatley** [Esri/geoportal-server#180]
Is there an issue with the server again? The last time we encountered this the XML schema server was down?

**Comment by mhogeweg** [comment]
looks like the eden site now requires an account to login. we'll have to look at an alternative site for referencing the ISO XSD.

**Comment by gcampanile** [comment]
We have a similar issue because the Italian profile requires GML 3.2 and the 2007 ISO repository does not include the srv schema. For INSPIRE service metadata I found this schema location:  http://ngdc.noaa.gov/metadata/published/xsd/schema.xsd. It works fine for me, I don't know if it's good for Gemini.
Gianni

**Comment by pbatley** [comment]
Marten/Gianni,
Can you advise where I need to make the config changes to point to a different schema, please?

Many thanks..
Paul

**Comment by gcampanile** [comment]
The eden schema is the in definition files for the profile.
For example, for gemini profile you should modify the file WEB-INF\classes\gpt\metadata\iso\gemini\gemini-iso-19119-definition.xml and subsitute  line 21:
  xsdLocation="http://eden.ign.fr/xsd/isotc211/isofull/20090316/srv/srv.xsd"
with
xsdLocation="http://ngdc.noaa.gov/metadata/published/xsd/schema.xsd"
please note that I had tested this with another, custom, profile, not with general 19119 ones.
Before going into modification of the definition file you might want to try on a metadata xml record using some XML validators (not only syntax check).
Gianni

**Comment by mhogeweg** [comment]
I'm checking with @tedhabermann [over on the ISO-TC211 repo](https://github.com/ISO-TC211/XML/issues/118) for a good location where ISO XSD are permanently hosted.

**Comment by mhogeweg** [comment]
per @jacimice: use

http://www.ngdc.noaa.gov/metadata/published/xsd/schema.xsd

while likely long-term available, it would be nice if ISO would host these publicly themselves.

**Comment by mhogeweg** [comment]
The official namespace for 19115/19139 is/was: http://www.isotc211.org/2005/  schema location here: http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/ 

The IGN xsds included some standards that were under development that weren’t available anywhere else at the time.

ISO is consolidating all the namespaces to here: http://standards.iso.org/iso/ 
See 19139, 19115-3 (new version – soon to be approved), 19110, 19157 (soon to be approved), etc.

**Comment by smrazgs** [comment]
http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/  does not have ISO19119 implemented. The NGDC schemas include an ogc implementation of 19119; you can also use http://schemas.opengis.net/csw/2.0.2/profiles/apiso/1.0.0/apiso.xsd
