### ISSUE TITLE
Publish metadata with a status of “Draft” if metadata is invalid

### ISSUE THREAD

**Issue by eggwhites** [Esri/geoportal-server#181]
Please add the ability to publish metadata with a status of “Draft” if metadata is invalid, instead of rejecting the document. This allows users to publish metadata and then open it up in the geoportal metadata editor for further editing (understanding also the limitations of the editor, as cited in https://github.com/Esri/geoportal-server/wiki/Online-form-editing-for-all-publication-methods).

**Comment by gcampanile** [comment]
Fully agree. I would suggest some more enhancements to simplify the process of converting/ adapting an existing repository: 
- publish (from a file) a record in draft if invalid (as requested by eggwhites)
- publish (when harvesting) records in draft if invalid. This can also be controlled  by adding a flag to the repository to choose the behaviour, discard or publish in draft.
- Use a specific profile editor for a metadata record This is very useful with custom profiles, to avoid manually editing of XML files.

Gianni

**Comment by zguo** [comment]
while we can try to publish and set the document status to draft mode, what the publisher will do with it afterwards as some of the invalid record might not be able to open by an editor? in case of harvesting you may have vast amount of records published as draft. it seems not realistic to manually edit large amount of invalid data either.

**Comment by smrazgs** [comment]
I agree, if a harvest yields a lot of invalid records, manually editing individual records is not a great solution, but for the case where there is a manageable number of problem records, its still a desirable feature. As far as content that might be lost by the editor, I'd say its up to the catalog manager to handle that in an input XSLT that either puts content where it will be preserved (like putting CSDGM entity attribute metadata in the abstract), or puts a note in the metadataMaintenance section to note that some content was lost in translation...

**Comment by zguo** [comment]
We can add a parameter to gpt.xml, set the option to false by default, an admin can enable draft mode if they choose to and know the implication.

**Comment by pandzel** [comment]
Registration page, Upload page - checkbox when checked then metadata will be upload as draft if validation failed. Code in 'develop' branch.
