### ISSUE TITLE
help with customizing "collections" values

### ISSUE THREAD

**Issue by lkutner** [Esri/geoportal-server#184]
New user question ... someone else set up our internal geoportal with custom values for "collections". I've been poking around in the files but haven't yet figured out where I do edits to the collections values?

When I'm logged into our geoportal as an admin & do "view source" - here's what's in the address bar and below that the beginning of the section with the collection values.

view-source:http://10.10.10.26:8080/geoportal/catalog/main/home.page

<td class="formLabelColumn"><label for="mmdForm:mmdCollection">
Is part of:</label></td>
<td class="formInputColumn"><select id="mmdForm:mmdCollection" name="mmdForm:mmdCollection" size="1">	<option value="" selected="selected">Any</option>
	<option value="1000">Boundaries_Administrative</option>

Thank you!

**Comment by mhogeweg** [comment]
hi, have you reviewed the documentation on collections on the wiki?

https://github.com/Esri/geoportal-server/wiki/Collections
