### ISSUE TITLE
Set agent http header to specific value

### ISSUE THREAD

**Issue by mhogeweg** [Esri/geoportal-server#186]
Some sites are blocking requests from http clients with the generic agent header value 'apache' or such. To make requests from Geoportal Server more recognizable, we should set the header to an identified value. while no guarantee on not being blocked or uniqueness or such, it gives some recognizable source of the requests. 

this plays particularly for harvesting and federated search.

**Comment by pandzel** [comment]
Implemented in 1.2.7
