### ISSUE TITLE
Standard Metadata of a map service not available

### ISSUE THREAD

**Issue by mmorcal** [Esri/geoportal-server#188]
Hi, 

I have edited the metadata of a Map Document (Mxd) with the ISO 19139 in ArcCatalog. I have validated the data, and it's ok. Then I've published the map service in ArcGIS Server and I can view metadata information if I go to:

http://myServer:6080/arcgis/rest/services/TestService/MapServer/info/metadata

But when I register my ArcGIS Server with Geoportal,only the basic metadata information of the service (such as title, description and tags) are getting saved to geoportal database.

If I export the xml of my map service and then I register it with Geoportal, I can view and search all metadata information.

How can I register service maps with the ISO 19139 metadata associated?

Thanks!

**Comment by mhogeweg** [comment]
currently we don't ingest the full metadata that is attached to a service. we have that on the roadmap though.

**Comment by mmorcal** [comment]
Thanks for your reply.

Then, I'll publish the exported xml. 

Is there any way to related de xml with ISO format with the registered map service?

**Comment by mhogeweg** [comment]
yes there is. in the ISO 19119 for services there are elements that can contain the service endpoint. 
See section Identification > Resource > Operation.

here is a simple example:
http://gptogc.esri.com/geoportal/catalog/search/resource/details.page?uuid=%7B5EA3BED7-B953-49AA-A9EC-FBF1364D0F74%7D
