### ISSUE TITLE
Setting Metadata Policy  Access

### ISSUE THREAD

**Issue by Zurvan** [Esri/geoportal-server#189]
Hello,
I have some CSW services (Registration Method) harvesting extern metadatas, but the access is set to "Unrestricted" for the new synchronize content.
I've checked the gpt.xml file and the Metadata Access Policy is set as "restricted" yet.
Do you have un solution to set all the new synchronize ressources to "Restricted" ? 

Geoportal version : 1.0.14

Thanks for your answer, best regards

**Comment by zguo** [comment]
currently records were always set to unrestricted when harvest, the items can be manually moved to a restricted group though.
