### ISSUE TITLE
Refresh AGS to AGP

### ISSUE THREAD

**Issue by willmartinpe** [Esri/geoportal-server#191]
I was able to do an intial harvest of AGS services into the geoportal.
After initial harvesting  ArcGIS services how to refresh the connection to reflect the addition or deletion of services on the ArcGIS server.
It does not seem to update though I have added some new AGS services. The new ones do not appear in the geoportal

**Comment by mhogeweg** [comment]
hi, in the registration page there are options for setting the harvesting frequency. the default is 'manual only'. if you change this to once a day, the geoportal will go out to the server and refresh what it knows from this server on a daily basis.

**Comment by willmartinpe** [comment]
How do I do change the refresh frequency for an existing connection?


William A Martin, P.E., A+, GISP      mailto:william.a.martin@usace.army.mil 
100 West Oglethorpe Avenue 
Savannah, GA 31401-3604 
CESAS-EN-HD
OFC: (912)652-5543 
FAX: (912)652-5252 
Either do, or do not, there is no 'try'. 


-----Original Message-----

**Comment by mhogeweg** [comment]
Hi William,

You can go to the registration page of the ArcGIS Server:

[cid:image002.jpg@01D12772.297985C0]

Click the icon with the pencil (third from the left) to open the registration page. You will see the option on how often the synchronization should happen. From this page you could also schedule the harvest directly.


[cid:image004.jpg@01D12772.297985C0]

**Comment by willmartinpe** [comment]
When I gp to the registration page I click URL then enter the url to my REST services then I click fresh daily but it gives me:
Registration with identical host URL already exist

How to get past this?

William A Martin, P.E., A+, GISP      mailto:william.a.martin@usace.army.mil 
100 West Oglethorpe Avenue 
Savannah, GA 31401-3604 
CESAS-EN-HD
OFC: (912)652-5543 
FAX: (912)652-5252 
Either do, or do not, there is no 'try'. 


-----Original Message-----
