### ISSUE TITLE
Harvesting vector (geodatabase) data

### ISSUE THREAD

**Issue by willmartinpe** [Esri/geoportal-server#192]
. How to bring vector (geodatabase) data into the Geoportal 3. How to add Geoportal items to ArcMap and perform 'clip and ship'

**Comment by mhogeweg** [comment]
hi, layers in a geodatabase can be registered in Geoportal Server directly from ArcMap using the publication add-in. please see this article on the wiki:

https://github.com/Esri/geoportal-server/wiki/Geoportal-Publish-Client

**Comment by mhogeweg** [comment]
regarding clip/zip/ship, this can be configured in Geoportal Server by following the instructions in this wiki article:
https://github.com/Esri/geoportal-server/wiki/DataDownload-Tab

**Comment by willmartinpe** [comment]
I got the publisher client to work and ran it in ArcMap.
I did not get anything as to what I was publishing.
It came back with a message that publishing was complete which I assume means successful,
I do not see anything new in the Geoportal to indicate anything happened.

I must be missing something.

will

William A Martin, P.E., A+, GISP      mailto:william.a.martin@usace.army.mil 
100 West Oglethorpe Avenue 
Savannah, GA 31401-3604 
CESAS-EN-HD
OFC: (912)652-5543 
FAX: (912)652-5252 
Either do, or do not, there is no 'try'. 


-----Original Message-----

**Comment by willmartinpe** [comment]
I under5stand how to run the tool now.

William A Martin, P.E., A+, GISP      mailto:william.a.martin@usace.army.mil 
100 West Oglethorpe Avenue 
Savannah, GA 31401-3604 
CESAS-EN-HD
OFC: (912)652-5543 
FAX: (912)652-5252 
Either do, or do not, there is no 'try'. 


-----Original Message-----
