### ISSUE TITLE
Is it possible to create resource from secure arcgis service url that require user&pw to access?

### ISSUE THREAD

**Issue by mariczone** [Esri/geoportal-server#199]
I need to register metadata from secure arcgis service that require user and password.
How I do that? 

thanks you.

**Comment by mhogeweg** [comment]
you would have to fill in metadata for the service using the online editor or upload an XML. The geoportal server does not store passwords to secure services or such. Using the editor (or XML upload) you can register the link.

**Comment by mariczone** [comment]
Thank @mhogeweg
