### ISSUE TITLE
"Delete" - Apply action to the entire result set - Don't delete index in lucene

### ISSUE THREAD

**Issue by mariczone** [Esri/geoportal-server#203]
**Geoportal 1.2.6**
Apply "delete" with **Apply action to the entire results set** will only delete data in database but not in lucene index. It still can searchable via Geoportal after removed.
![step1](https://cloud.githubusercontent.com/assets/10164210/14096481/50492b2a-f593-11e5-8d7e-535d25b17d18.png)

Is anyone can confirm this is bug?
Thank you.

**Comment by pandzel** [comment]
We made it that way. 

Delete operation as well as approve/disapprove is done by removing or adding records from/into the Lucene index. That is quite a slow operation; you won't notice it if records are just few, but with thousands of records the latency is quite noticeable (and annoying). 

However, a background task 'CatalogSynchronizer' will update Lucene index once the job is finished, i.e. all the undesired records will be deleted from the index. More about it here: https://github.com/Esri/geoportal-server/wiki/All-gpt.xml-file-settings#Scheduler_Settings

I hope it helps.
