### ISSUE TITLE
Preview map basemap and ArcGIS Server/ArcIMS layers

### ISSUE THREAD

**Issue by slead** [Esri/geoportal-server#204]
The preview map [instructions](https://github.com/Esri/geoportal-server/wiki/Preview-Function) say "The Base Map checkbox will not display for ArcIMS or ArcGIS Server services because for these types of services, the service layer obscures what would be the basemap"

That doesn't seem to be correct - the whole point of the basemap is to appear below the service layer, right? Especially in the case of a point or line layer, the service layer won't obscure the basemap. Even if a polygon layer does obscure the basemap, it won't hurt to have it there.

Is it possible to enable the basemap toggle for ArcGIS Server/ArcIMS layers? thanks

**Comment by zguo** [comment]
The function for previewing the map services is there for ArcGIS services, adding/overalying basemap as background is doable but more complicate to implement due to projection issues, e.g. some service have custom projection (WKT), some service might not support reproject (e.g. tiles).
