### ISSUE TITLE
Error parsing XSD, schema=iso-19115 xsdLocation=http://www.isotc211.org/2005/gmd/metadataEntity.xsd

### ISSUE THREAD

**Issue by bmcvicker** [Esri/geoportal-server#205]
We are unable to create new ISO 19115 (Data) format metadata records using the dedicated editor on Geoportal, v 1.2.4.  We can still create other formats (FGDC, etc.) but need to use the ISO Data format.  This just started today, and nothing has changed in our geoportal configuration.  Can anyone shed some light on why this is happening and how to fix?

Thanks for your help.

**Comment by mhogeweg** [comment]
does your log give any hints? did nothing change in the configuration or on the web server?

**Comment by bmcvicker** [comment]
Hi,
Thanks for your reply.  We have found a change to our system setup that caused this error, so we think we have it fixed.
Thanks!

**Comment by bmcvicker** [comment]
Hello,

We are unable to add or edit any metadata records currently on our Geoportal site.  We see the following error message:

???Error parsing XSD, schema=iso-19115 xsdLocation=http://www.isotc211.org/2005/gmd/metadataEntity.xsd

Nothing has changed on our system side.  When I go directly to the isotc website (http://www.isotc211.org) it says the site is unavailable.  I’m guessing this is what is causing the error.  Can you tell me how to find out if and when the site will be back up?

Thanks,

Bethann McVicker
GIS Analyst
Pacific Disaster Center

**Comment by mhogeweg** [comment]
hi, the reference to the xsdLocation can be found in the editor definition files. for example for ISO 19115, see:
```
...\webapps\geoportal\WEB-INF\classes\gpt\metadata\iso\iso-19115-definition.xml
```

there you'll see the xsdLocation attribute (xpath = ```/schema/@xsdLocation```). making this blank will make Geoportal Server not look for the XSD.

**Comment by bmcvicker** [comment]
Thanks, Marten.  Could you clarify what you mean by “making this blank”.  Should we delete the whole line:

xsdLocation="http://www.isotc211.org/2005/gmd/metadataEntity.xsd[GML32]http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/gmd/metadataEntity.xsd"

Or just the part after the “xsdLocation=”?

**Comment by mhogeweg** [comment]
change
```
xsdLocation="http://www.isotc211.org/2005/gmd/metadataEntity.xsd[GML32]http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/gmd/metadataEntity.xsd"
```
to
```
xsdLocation=""
```

**Comment by bmcvicker** [comment]
Thanks Marten.  That seemed to do the trick!
Bethann
