### ISSUE TITLE
Metada with every Feature Layer (hundreds of feature layers)

### ISSUE THREAD

**Issue by andzejhelcom** [Esri/geoportal-server#206]
We are preparing to migrate a map service from Flex Viewer to Web AppBuilder. We would like to keep approach: one map viewer based entry point, but with a user friendly search of Feature layers.

We have hundreds of different Feature layers and metadata file on each Feature layer. We are considering to use ArcGIS Server for Features layers and Geoportal Server for Metadata. For layer searching we might use Geoportal Search Widget or other solution (depends on compatibility with Web AppBuilder).

We want all these Feature layers would be present in maps Layer List in Web AppBuilder as invisible. When search on metadata is performed there should be possibility to make correspondent Feature layer visible on the map.

So the question is: what is the best way to publish Feature layers and metadata so they would be connected to each other? We do not want to publish each Feature layer as different service, because of amount of Feature layers. 

Any ideas how to achieve this?

Kind regards,
Andzej

**Comment by andzejhelcom** [comment]
I thouhgt I found a solution to connect each metadata with correspondent feature layer published on ArcGIS Server. But there seems to be a bug and I have no solution. 

What I do is before publishing I edit metadata in ArcCatalog and mark that it is Online resource and add link to published on ArcGIS Server layer http://servername:6080/arcgis/rest/services/ForTests/TestMetadataService/MapServer/0 

When I publish this metadata the link "Add to Map" appears in Geoportal. But when I click it the whole service is added to the map, not specified layer.

Is there a solution to add specific layer to map, not the whole service?

**Comment by zguo** [comment]
not sure if the issue is to the flex viewer or web app builder widget, for flex viewer, it will always add the service (layers can be turned on/off in the layer list), if it is to web app builder widget, it could be an good enhancement.

**Comment by andzejhelcom** [comment]
I think this issue is not Flex Viewer nor Web Appbuilder, but Geoportal itself, but I might be wrong. Published metadata is not connected to specified Feature layer within a service published on ArcGIS Server, but to a whole service. 

Can it be fixed some how? I wonder if I can do it myself (I have some Java programming experience), just need to be pointed where I should look in Geoportal sourcecode to fix it.

**Comment by mhogeweg** [comment]
check out this [service catalog](http://gptogc.esri.com/geoplatform/rest/find/document?f=searchpage). the first item listed is a layer in an ArcGIS Server service that is the result of Geoportal Server harvesting the ArcGIS Server instance. 

Select the [preview](http://gptogc.esri.com/geoplatform/catalog/search/resource/livedata-preview.page?uuid=%7BFD5A3E11-6002-4151-B522-656CD8C2217C%7D&url=http%3A%2F%2Fwebgis2.wr.usgs.gov%2FArcGIS%2Frest%2Fservices%2FTitan_global_gis%2FMapServer%2F212&resourceType=ags&info=%2Fgeoplatform%2Frest%2Fdocument%3Ff%3Dhtml%26showRelativeUrl%3Dtrue%26id%3D%257BFD5A3E11-6002-4151-B522-656CD8C2217C%257D) link to see that we draw only this 1 layer. Click [open](http://webgis2.wr.usgs.gov/ArcGIS/rest/services/Titan_global_gis/MapServer/212) to go to the layer page in the services directory on the server).

We should be able to configure for example ArcGIS Online map viewer to startup with individual layers like [this example](http://www.arcgis.com/home/webmap/viewer.html?url=https://tigerweb.geo.census.gov/ArcGIS/rest/services/Census2010/Labels/MapServer/110).

I'll add this as an enhancement for our 1.2.7 release.

**Comment by andzejhelcom** [comment]
As I understand there are separate layers in this catalog service. But metadata are poor there, it seems metadata are generated automatically or takem from ArcGIS Server. As far as I know, I can't store metadata created with ArcCatalog on ArcGIS Server. So not sure if harvesting the ArcGIS Server will help me to solve the problem (find and add to map layer searching metadata).

I'm not familiar with harvesting. Could you, please, point me to right documentation on it, and I see if this is what we need.

**Comment by pandzel** [comment]
Per Marten's request, I have added "Add to Map" link for any map service layer if the map is an ArcGIS online map viewer. In 'develop' branch now.
