### ISSUE TITLE
Additional Options dialog problem

### ISSUE THREAD

**Issue by JoannaAniserowicz** [Esri/geoportal-server#208]
I've deployed geoportal server in version 1.2.6 and I have problem with Additional Options dialog. It simply doesn't appear. In console (after clicking a link) there is an error "Uncaught TypeError: Cannot set property 'refreshOnShow' of undefined". I've checked sandbox site (http://gptogc.esri.com/geoportal/) and there is the same error.

**Comment by mhogeweg** [comment]
hi, what browser are you using?

**Comment by JoannaAniserowicz** [comment]
Hi,
Problem exists in:
Chrome:
error: "Uncaught TypeError: Cannot set property 'refreshOnShow' of undefined"
Firefox:
TypeError: dj is undefined in line dj.refreshOnShow = true;
IE:
similar error to this in Chrome

Before these errors there is in console another message: 
init.js:620 dojo/parser::parse() error TypeError: Cannot read property 'toString' of undefined.
Maybe this is a real problem?

**Comment by mhogeweg** [comment]
odd as I can see this dialog in all my browsers (chrome, FF, IE). is your site publicly accessible?

**Comment by JoannaAniserowicz** [comment]
Hi,
Yes, my site is publicly accessible but problem exists even in sandbox site.
I know what causes the problem - when I changed my browser's language to english everything works fine (default was polish). Unfortunately my clients have polish browsers so what should I do to fix this?

**Comment by JoannaAniserowicz** [comment]
I figured it out - just had to change djConfig in lookAndFeel.jsp to "pl". Thank you for your comments!

**Comment by mhogeweg** [comment]
alright! still curious to see your site :-)
