### ISSUE TITLE
Possible to Upload/Edit MXD XML Metadata?

### ISSUE THREAD

**Issue by MapZombie** [Esri/geoportal-server#211]
Hi there,

My organization is looking to implement a Geoportal.  However a very important feature is the ability to edit metadata produced from MXD files.  
Basically is there any way possible to give users the ability to **upload an XML file from an MXD, have geoportal retain the existing metadata and then allow users to edit and fill in the final fields**?

**Comment by mhogeweg** [comment]
hi, when you manage your map document (mxd) in ArcMap, you can also create metadata for it there. then you can upload the metadata (.xml located with .mxd) to Geoportal Server directly. From there, users can still edit the metadata in Geoportal Server. 

If you then want the .xml that's located with the .mxd to have the same metadata, you could download the .xml from Geoportal Server again and associate it with the map document.

**Comment by MapZombie** [comment]
Thanks so much for your reply, Marten.

We want to have the ability to have users use mostly drop down attributes for our metadata and strongly prefer not to edit within ArcMap.  However you said users can edit the metadata once uploaded to Geoportal, directly?   Could you explain how?  Thanks

**Comment by mhogeweg** [comment]
Check out this wiki page:
https://github.com/Esri/geoportal-server/wiki/All-gpt.xml-file-settings#additional-settings

the setting to enable editing regardless of publication method is ```catalog.enableEditForAllPubMethods```

After uploading the xml to Geoportal Server, with the above setting, users can edit the metadata in the Geoportal XML Editor.

**Comment by MapZombie** [comment]
Awesome, thank you!
