### ISSUE TITLE
Where can I find the ISO 19139 files?

### ISSUE THREAD

**Issue by slead** [Esri/geoportal-server#212]
I need to create a custom profile as explained at https://github.com/Esri/geoportal-server/wiki/Add-a-Custom-Profile and the customer wants to based their profile on ISO 19139, with some modifications.

Which is the best existing file to use as a starting point?

I can't see ISO 19139 in the geoportal\WEB-INF\classes\gpt\metadata\ directory, although iso-19119-definition.xml does contain referenes to 19139.

(I'm not an expert at the various ISO standards so I'm a bit confused by it all... thanks)

**Comment by slead** [comment]
I can see some files under \geoportal\WEB-INF\classes\gpt\gxe\iso\iso19139 but 19139 is not mentioned in my schemas.xml file, so 19139 doesn't show when I choose _> Add > Use dedicated editor to create metadata manually_

I tried adding 19139 to schemas.xml but this doesn't cause 19139 to show:

```
  <schema fileName="gpt/metadata/iso/iso-19115-definition.xml"/>
  <schema fileName="gpt/metadata/iso/iso-19119-definition.xml"/>
  <schema fileName="gpt/gxe/iso/iso19139/iso19139-dataset-editor.xml"/>
```

<img width="399" alt="screen shot 2016-05-31 at 3 06 59 pm" src="https://cloud.githubusercontent.com/assets/133596/15663761/5b550d1a-2741-11e6-8811-ac77df04ef8a.png">

I suspect I'm misunderstanding something fundamental here.

**Comment by mhogeweg** [comment]
hi Stephen, ISO 19139 is just the xml encoding of 19115/19119. the two editors apply 19139 encoding rules already, so I would not expect a separate 19139 editor.

in the ```.../gpt/metadata``` folders you just make the definition of the schema. a good example ISO profile is ```.../gpt/metadata/iso/inspire```. there is a template (an example file used with defaults), a definition file (where some stylesheets are listed for details, csw responses etc), the interrogation rule (how does geoportal server recognize the schema?), and most importantly: a reference to the Geoportal XML Editor ```</editor>```.

That editor (for INSPIRE for example) is in ```.../gpt/gxe/iso/iso19139/profiles/inspire```.
