### ISSUE TITLE
Using a local or network drive for harvest?

### ISSUE THREAD

**Issue by MapZombie** [Esri/geoportal-server#213]
Hello,

I would love to know if it is possible to use a **network drive as a source for harvesting**?  Basically we have a folder structure of maps and metadata and would like to **retain the folder structure while having geoportal automatically pull and update the metadata from a network drive.**

Is this possible?  I see from the geoportal we need to have a URL setup for harvest or any of the options:
 URL	 ArcGIS	 Esri MS	 OAI	 WAF	 CSW	 THREDDS	 ATOM	 DCAT

I appreciate any help you can provide!  Thanks.

**Comment by mhogeweg** [comment]
hi, there are two ways to accomplish this. One is to use the desktop addin for publishing. this can be used to push the metadata of a folder and sub-folders to Geoportal (including file/personal geodatabases inside those folders). 

The other option is to implement the UNC harvester as described in:
https://github.com/Esri/geoportal-server/wiki/Extending-the-Web-Harvester#step-by-step-example

Note that the references to the network drive will be in UNC paths, not URL. this limits who will be able to get the data to those who have access to the UNC paths.

**Comment by MapZombie** [comment]
Thank you.  This looks very promising.  I tried to extract the sample files as per the README text (see below).  However the same files were not over written and it appears much of the structure between v 1.2.2 and our version 1.2.6 is different.  Just curious if these instructions can still apply to v1.2.6, or if you had any further tips to get this working?

Thanks again.

> This package contains source code for sample UNC harvest client.
Example has been prepared using Geoportal Server ver. 1.2.2 as a code base.

Unzip the content into your Geoportal Server root folder and rebuild entire project. 

The following files will be overwriten:

src/com/esri/control/harvest/HarvestController.java
src/com/esri/control/publication/ManageMetadataController.java
src/com/esri/control/webharvest/protocol/ProtocolFactories.java
src/gpt/resources/gpt.properties
www/catalog/harvest/harvestBody.jsp

>

**Comment by mhogeweg** [comment]
adding @pandzel who develops this part of Geoportal Server

**Comment by MapZombie** [comment]
Hello @pandzel , looking forward to your input this matter.  Thanks.

**Comment by pandzel** [comment]
As far as I can remember, the example has been published a while ago and it's quite possible that is not compatible with the recent version of the Geoportal Server code. However, the general idea described in the example is still valid.

**Comment by MapZombie** [comment]
Thanks, unfortunately I don't have much experience working with Java.  I will try to learn to implement this.

**Comment by MapZombie** [comment]
If you wouldn't mind would you please explain the folder structure changes between 1.2.2 and 1.2.6 as I am completely lost right now in trying to implement the java files included in the example files and tutorial.

Thank you.

**Comment by pandzel** [comment]
I am not sure about these changes; you would have to use diff tool or something like that. Besides, there is less about changes in the folder structure than the content.

If your goal is to get data from your local disk into the Geoportal Server without getting much into the code, it might be simpler option for you: you could mount that folder as a virtual directory under IIS, then harvest it using WAF protocol.

**Comment by MapZombie** [comment]
Thanks @pandzel the IIS option makes the most sense.

**Comment by mgg-eagle** [comment]
Could you add a UNC harvester as a core part of geoportal server?  I think this is functionality that many users would appreciate.  Thanks.

**Comment by MapZombie** [comment]
Absolutely agree with @mgg-eagle .  I think it would be a great idea to add UNC harvesting, out of the box.
