### ISSUE TITLE
What is the syntax for searching another Esri Geoportal Server?

### ISSUE THREAD

**Issue by slead** [Esri/geoportal-server#221]
I'm trying to add another Esri Geoportal Server to the "Records Shown From" section, as per https://github.com/Esri/geoportal-server/wiki/Add-an-OpenSearch-endpoint-for-Federated-Search

What is the syntax for adding another Esri Geoportal Server, eg http://gptogc.esri.com/geoportal?

Specifically, what should the `endPointSearchUrl` point to in the case of http://gptogc.esri.com/geoportal? Can you give an example of the changes to the GptXslSearchProfiles.xml file?

Thanks

**Comment by mhogeweg** [comment]
Hi Stephen, you would regulate the other geoportal's CSW get capabilities url in the 'register resource on the network' CSW tab. Choose geoportal as the profile.

M
