### ISSUE TITLE
DCAT output missing "temporal" element

### ISSUE THREAD

**Issue by torrin47** [Esri/geoportal-server#224]
Odd that this went unnoticed for so long, particularly given how much emphasis was placed on improving date formatting at 1.2.6, but the dcat output appears to completely omit the "temporal" element, despite default COTS configuration, and we've not been able to enable it. As a confirmation of this behavior we've noted that the dcat output from the Esri sandbox instance has no occurrences of the dcat "temporal" extent element.

http://gptogc.esri.com/geoportal/rest/find/document?f=dcat&max=5000

Thoughts?

**Comment by zguo** [comment]
Hi Torrin,

We will take a look , it might be indexing or records without temporal info. can you please provide a couple of sample metadata to try out.

Thanks!

ZhongPing

**Comment by torrin47** [comment]
Would it be more useful to have a couple of model records or a wide range of possibilities?  When I look around in our public web accessible folders, I see that most records have some sort of temporal element, though some specify ground condition, some publication date, and others advertise a range with no associated description.
https://edg.epa.gov/WAFer/EDG/
https://edg.epa.gov/WAFer_harvest/FGDC/
the free text nature of these elements in CSDGM certainly makes date formatting a challenge, and this element is only “mandatory if applicable”, but there are enough valid dates present that at least some records should have temporal elements on the other end.

**Comment by zguo** [comment]
Indeed there was a bug, I’ve posted the fix on gptogc, you might try if particular date element/format works for you, the simplest way to test is to upload a record, approve, do a search for that particular record and then click on the dcat link to see if temporal element is there.

Thanks!

ZhongPing

**Comment by torrin47** [comment]
Excellent, I see things working on gptoc now, that’s good enough for us, we’ll incorporate it with the next release.  Much appreciated.

**Comment by zguo** [comment]
fixed in 1.2.7
