### ISSUE TITLE
How to purge/remove all records from the database

### ISSUE THREAD

**Issue by slead** [Esri/geoportal-server#225]
I accidentally imported thousands of records from http://gptogc.esri.com/geoportal while testing the CSW harvesting.

How can I quickly delete all records from the database so I can start afresh?

Will it cause any problems if I use PGADMIN and delete the records from *gpt_resource* and *gpt_resource_data*? If that's a valid approach, do I need to create new indexes (etc) after doing this?

Thanks

**Comment by mhogeweg** [comment]
You'll want to do this from the geoportal admin page. If you enabled the 'apply to all' option you would select the records based on the site they were harvested from. Then select the first page and select the 'apply to entire selection' option before selecting 'delete' from the drop down. 

This apply to all option is set in gpt.xml.

**Comment by slead** [comment]
Apply To All is what I was missing - thanks

**Comment by slead** [comment]
After doing that, Pgadmin shows that those tables now contain 0 records. But searching within This Site still lists thousands of records:

![screen shot 2016-06-21 at 12 53 52 pm](https://cloud.githubusercontent.com/assets/133596/16216586/43ecfe52-37af-11e6-954d-01a82c1fbcba.png)

Trying to view the Details of a record shows that it has been deleted:

![screen shot 2016-06-21 at 12 54 03 pm](https://cloud.githubusercontent.com/assets/133596/16216592/4d19e418-37af-11e6-8c1c-7d8a6a89a8a4.png)

So it appears that there's an index out of synch? Also _C:\Lucene_ still contains ~50Mb of data, which could be the old records, perhaps?

I tried restarting Tomcat and restarting the whole PC but neither changes the fact that thousands of records are listed when running a search on This Site.

Any further clues? thanks

**Comment by mhogeweg** [comment]
yes, the index will need to be updated. you can wait for the scheduled task to kick in. you should also be able to restart tomcat as that typically also starts the sync. obviously, you could remove the index files and then reapprove all remaining records. that will also typically result in rebuilding the index.

**Comment by slead** [comment]
restarting Tomcat again didn't work, so I guess I'll wait for the scheduled task to kick in. Is there a way to determine when this will occur?

**Comment by mhogeweg** [comment]
see the [scheduler settings](https://github.com/Esri/geoportal-server/wiki/All-gpt.xml-file-settings#Scheduler_Settings) in gpt.xml. it allows you to set an interval for re-indexing, but you could also force it to happen at a certain time (say 5 minutes after now).
