### ISSUE TITLE
Dedicated editor > database > XML files?

### ISSUE THREAD

**Issue by MapZombie** [Esri/geoportal-server#226]
Hello,
Where does metadata dedicated editor created metadata get stored?   We would like to have a copy of the XML file that geoportal produces when using the GXE and save it with the actual file (PDF, MXD etc). 

 
I believe the GXE saves the metadata in a database right now, is there a way to save a copy of the created XML to the source folder?

Thanks!

**Comment by mhogeweg** [comment]
Once published to Geoportal Server you can download the metadata individually from the administration page. You can also access the XML directly for a known document using this REST endpoint:

http://gptogc.esri.com/geoportal/rest/document?id=%7BEAE3529B-6904-40EF-8EE6-3FEB5AEA1750%7D

or

http://gptogc.esri.com/geoportal/rest/document/%7BEAE3529B-6904-40EF-8EE6-3FEB5AEA1750%7D

where the id is the identifier of the document as assigned by Geoportal Server.

In Geoportal Server Harvester 2.0 we have an ability to harvest an entire Geoportal instance into files on disk. please see the [harvester 2.0 repository](https://github.com/Esri/geoportal-server-harvester) for more information on that.

**Comment by MapZombie** [comment]
Thanks @mhogeweg .  What we are looking for is a copy of the XML to be saved alongside the actual file it is referencing.  I will look into a script to see if this is possible.  Did you have any other suggestions on achieving this?

**Comment by MapZombie** [comment]
For example when using the dedicated metadata editor we wrote code that would create an additional SAVE XML button that allowed the user to save the file as XML anywhere on their PC.

**Comment by MapZombie** [comment]
Going through the new features of version 1.2.7 it can:

> Ability to harvest metadata to a local folder in addition to geoportal repository

Could the team elaborate on how to go about doing this?  Thanks

**Comment by MapZombie** [comment]
I have added the following to gpt.xml in version 1.2.7
`<webharvester>
	<dataProcessorFactory enabled="true" className="com.esri.gpt.control.webharvest.extensions.localfolder.LocalFolderDataProcessorFactory" name="localfolder" rootFolder="c:\data"/>
</webharvester>`

Yet it hasn't yielded any XML files inside my local folder...
