### ISSUE TITLE
Harvest to local drive GP 1.2.7 Feature

### ISSUE THREAD

**Issue by MapZombie** [Esri/geoportal-server#228]
Going through the new features of version 1.2.7 it has the:

> Ability to harvest metadata to a local folder in addition to geoportal repository

     
I have added the following to gpt.xml in version 1.2.7
`<webharvester> <dataProcessorFactory enabled="true" className="com.esri.gpt.control.webharvest.extensions.localfolder.LocalFolderDataProcessorFactory" name="localfolder" rootFolder="c:\data"/> </webharvester>
`
Yet it hasn't yielded any XML files inside the c:\data folder.  

Am I missing anything here?

**Comment by MapZombie** [comment]
I am testing this by using the dedicated metadata editor and then saving.

**Comment by MapZombie** [comment]
**From gpt log** 
`Jun 29, 2016 3:20:25 PM com.esri.gpt.control.rest.ManageDocumentServlet execute
FINE: HTTP PUT, http://cal8783:8079/geoportal1/rest/manage/document?publicationMethod=editor&errorsAsJson=jErr&id=D8817C3D-D4DA-472B-A19C-5BDD40D29233
Jun 29, 2016 3:20:25 PM com.esri.gpt.framework.sql.DatabaseReference openConnection
FINE: Connection opened for gpt, jndiName: jdbc/gpt, productName: Oracle, driver: Oracle JDBC driver 11.2.0.3.0
Jun 29, 2016 3:20:25 PM com.esri.gpt.control.rest.ManageDocumentServlet executePut
FINE: Approving of uploaded documents through the REST with 'approve' flag: 
Jun 29, 2016 3:20:37 PM com.esri.gpt.framework.sql.DatabaseReference closeConnection
FINE: Closing connection for gpt, jndiName: jdbc/gpt`

**From localhost access log:**
`10.101.24.117 - - [29/Jun/2016:15:19:52 -0600] "GET /geoportal1/catalog/publication/createMetadata.page HTTP/1.1" 200 15406
10.101.24.117 - - [29/Jun/2016:15:19:56 -0600] "POST /geoportal1/catalog/publication/createMetadata.page HTTP/1.1" 200 16248
10.101.24.117 - - [29/Jun/2016:15:19:58 -0600] "GET /geoportal1/gxe/definition?key=iso-19115&f=json&dojo.preventCache=1467235198820 HTTP/1.1" 200 256030
10.101.24.117 - - [29/Jun/2016:15:20:37 -0600] "PUT /geoportal1/rest/manage/document?publicationMethod=editor&errorsAsJson=jErr&id=D8817C3D-D4DA-472B-A19C-5BDD40D29233 HTTP/1.1" 201 -
10.101.24.117 - - [29/Jun/2016:15:20:53 -0600] "POST /geoportal1/catalog/publication/gxeEditor.page HTTP/1.1" 200 116888
10.101.24.117 - - [29/Jun/2016:15:21:03 -0600] "POST /geoportal1/catalog/publication/manageMetadata.page HTTP/1.1" 200 116947`


I couldn't find anything on the webharvester posting to the local drive.  Any insight would be greatly appreciated.

**Comment by MapZombie** [comment]
Any ideas? 

> Synchronization and Publishing

Support for robots.txt when harvesting, see Being-a-Good-Robot
**Ability to harvest metadata to a local folder in addition to geoportal repository**

**Comment by zguo** [comment]
Please try to register a site and then harvest to see if the local folder will be populated.

**Comment by MapZombie** [comment]
Hi @zguo , I am trying to implement the ability to harvest a local copy of the XML file when users goto "Use a dedicated editor" to create new metadata.

**Comment by mhogeweg** [comment]
there is an option in gpt.xml that enables editing XML files you uploaded. the workflow would be:
- enable editing regardless of publication method
- upload your XML file
- open in online editor

**Comment by MapZombie** [comment]
@mhogeweg I do have metadata editing enabled as you layed out 
But the workflow I am looking to implement is:

- Create metadata using dedicated metadata editor
- Save
- Have a copy of the new XML file saved **locally** as well as in the Geoportal DB

Our users have MXDs, PDFs etc that they need to catalog.  We want users to create new metadata for their MXDs using the editor.  And ideally have the XML file placed in the same location as the MXD, or if this is not possible all in one central local location.

**Comment by mhogeweg** [comment]
your users with MXD should create their metadata in ArcGIS Desktop. from there they would publish map services and such for example to ArcGIS Online or Portal for ArcGIS, both of which support metadata. If content is then exposed through the Open Data app for ArcGIS Online, the metadata flows all the way through to there.

**Comment by MapZombie** [comment]
Our users won't be using ArcGIS Desktop to edit their metadata unfortunately.  Getting back to the original question, would it be possible to have the > Ability to harvest metadata to a local folder in addition to geoportal repository
as mentioned in the features for version 1.2.7?

**Comment by mhogeweg** [comment]
that is possible from the administration page. since you'll be editing metadata from there and then need to save it to individual folders, the most practical path is to click the metadata download button for the item just created and save it to the right path and with the right name.

**Comment by MapZombie** [comment]
The download metadata button was available in  v1.2.6.

**Comment by mhogeweg** [comment]
it still is! in the administration page, select ![image](https://cloud.githubusercontent.com/assets/394890/16600640/f08d5c02-42bc-11e6-982f-655a4af66430.png) to download the desired metadata to a file.

**Comment by MapZombie** [comment]
Sorry, what I meant was that it isn't a new feature as outlined in:
https://github.com/Esri/geoportal-server/wiki/Geoportal-Server-1.2.7---What%27s-New

**Comment by mhogeweg** [comment]
those metadata enhancement features are indeed new and not what I understood you were trying to do with downloading metadata.
