### ISSUE TITLE
Issue about make record editable. Need guideline.

### ISSUE THREAD

**Issue by mariczone** [Esri/geoportal-server#232]
**Geoportal 1.2.7** has new function that make record editable such as record that come from upload **method to editable.**

but as we already know that geoportal **metadata editor is not exhaustive**. so some field may be not matching with geoportal editor.

Example: ISO 19115 Data XML(Upload)

```
<gmd:language>
  <gmd:LanguageCode codeList="http://www.loc.gov/standards/iso639-2/php/code_list.php" codeListValue="eng">eng</gmd:LanguageCode>
</gmd:language>
```

But in geoportal editor, For Element:Language we accept only **gco:characterstring** not **gmd:LanguageCode**
```

<gmd:language>
        <gco:CharacterString>eng</gco:CharacterString>
</gmd:language>
```

So, I try to customize editor but I need some hint to do it.
File: [XTN_Language](https://github.com/Esri/geoportal-server/blob/master/geoportal/src/gpt/gxe/iso/iso19139/xtn/gmd/metadataEntity/XTN_Language.xml) for using in editor of 19115
```
<?xml version="1.0" encoding="UTF-8"?>
<!-- gmd:language -->
<g:element xmlns:g="http://www.esri.com/geoportal/gxe" 
           xmlns:h="http://www.esri.com/geoportal/gxe/html"
           g:targetName="gmd:language"** g:minOccurs="0" g:maxOccurs="1"
           g:preferOpen="true" g:label="$i18n.catalog.iso19139.MD_Metadata.language"
           g:extends="$base/schema/gco/basicTypes/CharacterString_PropertyType.xml">
  <g:body>
    <g:element g:value="en"/>
  </g:body>
</g:element>
```

## What I want is customizing this file to accept both **gco:characterstring** and **gmd:LanguageCode** like below

```
<g:element g:targetName="gmd:language">
  <ifsuggest name="gco:CharacterString" g:extends="...use this form.."/>
  <ifsuggest name="gmd:LanguageCode" g:extends="...use this form.."/>
</g:element>
```

But I don't know how to do like these on this file.
Can u show me some guideline or hint or document about what can i do with these file?

Thank you.

**Comment by MapZombie** [comment]
Hi @mariczone .  Have you taken a look at the crash course document?  https://github.com/Esri/geoportal-server/wiki/GXE-Crash-Course  it helped me create some customizations.  Hopefully it can help you too.

**Comment by mariczone** [comment]
@MapZombie Thank you. That's what I need.
