### ISSUE TITLE
Upload same fileIdentifier XML File

### ISSUE THREAD

**Issue by mariczone** [Esri/geoportal-server#233]
The XML below is owner by publisher A.

```
<gmd:fileIdentifier>
        <gco:CharacterString>E00276C0-2724-467E-A923-E3D0400F34DB</gco:CharacterString>
</gmd:fileIdentifier>
<gmd:language>
        <gco:CharacterString>eng of Publisher A</gco:CharacterString>
</gmd:language>
```

If publisher B upload new XML file that contain XML like below

```
<gmd:fileIdentifier>
        <gco:CharacterString>E00276C0-2724-467E-A923-E3D0400F34DB</gco:CharacterString>
</gmd:fileIdentifier>
<gmd:language>
        <gco:CharacterString>eng of Publisher B</gco:CharacterString>
</gmd:language>
```

**New record of publisher B will replace or update old record of publisher A instead of create new record for publisher B.**

Because both xml contain same fileIdentifier ID.

I think it should alert some message about this record that contain this fileIdentifier has already exist in system by other owner. instead of replace content of other owner.

Thank you.

**Comment by mariczone** [comment]
I fixed these by customize method findExistingUuidFromField in ImsMetadataAdminDao class.

**Comment by mhogeweg** [comment]
perhaps you can submit a pull request for this?
