### ISSUE TITLE
Future Plans of v1.2.x with v2.0 knocking

### ISSUE THREAD

**Issue by MapZombie** [Esri/geoportal-server#235]
This is a question for the ESRI team, how long do you expect to continue to develop new releases for the 1.2.X version of Geoportal?  

I ask this as we in the midst of implementing a new spatial search engine, but would like to know if going with the 2.x line makes more sense for future proofing/support.  And whether this version will continue for a number of years? 

Thank you.

**Comment by mhogeweg** [comment]
you may expect more releases of 1.2.x, based on user feedback, bug reports, etc. however, our focus will shift to 2.x as we have functionality gaps to fill and new features to include (particularly regarding harvesting).

**Comment by mhogeweg** [comment]
that said, there are many 1.2.x implementations we will support in their use of Geoportal Server.
