### ISSUE TITLE
Custom ArcGIS XSL functions

### ISSUE THREAD

**Issue by torrin47** [Esri/geoportal-server#236]
We are adapting the standard ArcGIS.xsl stylesheet provided in ArcCatalog for use with Geoportal Server, and we are able to access the "Custom ArcGIS XSLT Functions" described here: 
http://desktop.arcgis.com/en/arcmap/10.3/tools/conversion-toolbox/xslt-transformation.htm
using the http://www.esri.com/metadata namespace.  However, we are seeing errors with the equivalent "res" namespace, supposedly referenced here: "http://www.esri.com/metadata/res" (obviously both URLs are dead-ends, but that in and of itself shouldn't be a dealbreaker).  We've not been able to track down any documentation for this res namespace nor where we might be able to find the libraries to add them to GeoPortal Server. Any thoughts or suggestions? The stylesheets are provided in a standard ArcGIS Desktop installation in the following directory:  ArcGIS\Desktop10.4\Metadata\Stylesheets.

**Comment by mhogeweg** [comment]
yes, I do expect you'll need one of the metadata libraries for this. I don't know if those are available in Java-compatible. I'll check with the metadata team

**Comment by mhogeweg** [comment]
closing per discussion with Aleta on 7/26/2016
