### ISSUE TITLE
Federated searching of CKAN site?

### ISSUE THREAD

**Issue by slead** [Esri/geoportal-server#238]
I'm aware of the method for configuring federated searching across other Esri Geoportal Server sites using CSW:

![screen shot 2016-08-11 at 3 03 41 pm](https://cloud.githubusercontent.com/assets/133596/17579108/ddde7f48-5fd4-11e6-905e-375ef2d6ea1b.png)

What is the method for configuring federated search across CKAN sites? Eg, is it possible to search within http://data.gov.au, which is based on CKAN?

**Comment by mhogeweg** [comment]
most CKAN sites implement pycsw, a python-based CSW interface. that could then be registered with Geoportal Server. This is for example how we interact with Data.gov. if pycsw is not available, if CKAN supports opensearch, that would be an alternative path (add the CKAN opensearch URL to gpt.xml).
