### ISSUE TITLE
Location of sample XSLT files

### ISSUE THREAD

**Issue by slead** [Esri/geoportal-server#239]
The page at https://github.com/Esri/geoportal-server/wiki/Use-an-XSLT-to-Render-the-Details-Page says:

> some sample xslts are available [online](http://arcscripts.esri.com/details.asp?dbid=14673); these can be used as a base but will likely need some adjustment for use with your geoportal

Unfortunately the URL (ArcScripts) has been redirected to ArcGIS Code Sharing, but the old content was not (bad site admin!).

Are the sample XSLT files available elsewhere?

**Comment by zguo** [comment]
the link (http://arcscripts.esri.com/details.asp?dbid=14673) seems works fine for me (with firefox), can you please double check, might be browser related.

**Comment by slead** [comment]
Perhaps inside Esri you're still able to get to ArcScripts? Externally they've redirected the entire http://arcscripts.esri.com url to http://codesharing.arcgis.com (and they haven't ported the content, so we can't get to the old content).

Are you able to download that sample XSLT file and upload to this GitHub thread? Thanks

**Comment by zguo** [comment]
here you go. https://esri.box.com/s/n126d0dp4g5d8ofhhd8mc6ukqi27b6ua
