### ISSUE TITLE
Harvest Issue

### ISSUE THREAD

**Issue by jacimize** [Esri/geoportal-server#244]
We currently have version 1.2.6 installed and when we tried to harvest service iso metadata from http://www.ncddc.noaa.gov/approved_recs/nos_new/nccos/services/, it would not harvest. We ran reports and it says that it could obtain, validate, and publish the records when we tried to harvest up a level at http://www.ncddc.noaa.gov/approved_recs/nos_new/nccos/ but it still did not work. We were able to successfully upload and publish individual records manually from the file.

**Comment by mhogeweg** [comment]
I harvested the services folder in to my dev environment. it succeeds, but it marks each of the documents as invalid:

http://www.ncddc.noaa.gov/approved_recs/nos_new/nccos/services/MHIMarine.xml FAILED FAILED 
Validation Error: Identification Information - Title: is required. 
Validation Error: /gmi:MI_Metadata/gmd:identificationInfo/gmd:MD_DataIdentification/gmd:citation/gmd:CI_Citation/gmd:title/gco:CharacterString 
Validation Error: Identification Information - Abstract: is required. 
Validation Error: Spatial Domain - West Bounding Longitude: is required. 
Validation Error: Spatial Domain - South Bounding Latitude: is required. 
Validation Error: Spatial Domain - East Bounding Longitude: is required. 
Validation Error: Spatial Domain - North Bounding Latitude: is required. 

the xpaths all refer to gmd/gmi, while I see your metadata uses srv:SV_ServiceIdentification. that may require an update to my validation rules (I may not have the latest metadata definitions), but in principle I can harvest the WAF. 

when you harvest the WAF, can you view the history reports and what messages do you see there?

**Comment by jacimize** [comment]
yes, I updated the definitions to include both gmd or gmi. I do not get an error message, it says that it successfully harvests and validates and publishes and gives the correct number in the report but when I go to view the records from resource they are not there and they are not shown in the search. When I upload the records individually it works well.

**Comment by jacimize** [comment]
FYI, I am using the schema definitions from http://www.ngdc.noaa.gov/metadata/published/xsd/schema/

**Comment by mhogeweg** [comment]
do you see the harvested documents in the administration page?

**Comment by jacimize** [comment]
no, just the metric in the reports

**Comment by mhogeweg** [comment]
hmm, can you send the ISO definition file you use (where you added gmi)?

**Comment by jacimize** [comment]
When I reviewed the definition file it looks like the issue was on our end when we upgraded geoportal versions and copied over the old definition files from our previous version. I corrected the definition file and it works perfectly!! Sorry!!

**Comment by mhogeweg** [comment]
:8ball:
