### ISSUE TITLE
Unable to search for resources after setting up Geoportal on Ubuntu 16.04 with postgresql 9.4.5 and tomcat 8

### ISSUE THREAD

**Issue by parnasoft** [Esri/geoportal-server#247]
I followed the instructions provided in wiki for this repo to install and configure geoportal.  I successfully registered an ArcGIS protocol (used this service U.S. Forest Service Invasive Species).   After I synchronized content waited for almost more than an hour.  I added 980+ documents related to this service.  I am still unable to search for any resource on my instance of the geoportal.  I am able to search on the sandbox ( http://gptogc.esri.com).  I double check all configurations and did not find anything obvious in the gpt and other logs.  

Any help will be appreciated.

**Comment by mhogeweg** [comment]
when you look in the administration page, what is the status of the harvested items? this needs to be 'Approved' in order for them to be findable.

**Comment by parnasoft** [comment]
@mhogeweg This is GK. All of the harvested items show Approved status.

**Comment by mhogeweg** [comment]
is your site public?

**Comment by mhogeweg** [comment]
can you open http://gptogc.esri.com/geoportal/rest/index/stats where you replace gptogc.esri.com with your domain name. this should tell you how many documents are in the index.

another action is to look in the gpt.xml configuration file where you have set the lucene index to be stored and then make sure it actually gets created.

**Comment by parnasoft** [comment]
No it is not.  My site is on a private network.

**Comment by parnasoft** [comment]
When try to open http://192.168.1.6:8080/geoportal/rest/index/stats, it shows a blank page.

**Comment by mhogeweg** [comment]
please check

```
    <catalog gptTablePrefix="GPT_">
		<lucene
			indexLocation="D:/data/geoportalserver/index"
```

the attribute ```indexLocation``` should be set to a valid folder where the geoportal has write access

**Comment by parnasoft** [comment]
I see _ka.fdt, .fdx, .fnm, .frq, .nrm, etc files under /usr/local/etc/lucene.

**Comment by parnasoft** [comment]
here is that section from my gpt.xml ( I followed the doc and it did not ask me to uncomment the section you are referring to)

<catalog gptTablePrefix="GPT_">       
    
      
    <lucene
        indexLocation="/usr/local/etc/lucene"
        writeLockTimeout="60000"
        useNativeFSLockFactory="true"
        analyzerClassName="org.apache.lucene.analysis.standard.StandardAnalyzer">

**Comment by parnasoft** [comment]
Another point I forgot to mention - I cant even browse the catalog.

**Comment by parnasoft** [comment]
OK.  I figured this out - it was pilot error.  The hazards of manually having to tweaking gpt.xml (not complaining).   I am now able to search and look at 

This line was the culprit - 
<parameter key="lucene.force.isPartOf" value=""/>
I had a garbage value like below
<parameter key="lucene.force.isPartOf" value="true"/>


What could help in the future is some hints on trouble shooting like which logs to look for and some examples of what to expect, etc.

**Comment by mhogeweg** [comment]
glad you found it.

**Comment by parnasoft** [comment]
Thanks for your support.  We can close this issue now.
