### ISSUE TITLE
Thumbnails do not appear in IE Browser from Search results

### ISSUE THREAD

**Issue by rmbradley** [Esri/geoportal-server#248]
Geoportal 1.2.5:

When comparing search results employing Downloadable Data filter and a specific text search, the Result set appears as normal on the right side of the page.  Expanding results reveals that although the thumbnails appear when using Chrome, they do not appear when using IE  (versions 9 and 11).  Examining the source from each browser reveals the following

Chrome and IE build this output row element in the results table from the Search (example Title is "BLM REA CBR 2010 & MBR Cheatgrass climatic habitat under current climate conditions).  All rows exhibit this issue.

---start row  Chrome--- (notice Chrome includes the "img" element)

`<td class="metadataCntTypIcon"><span id="frmSearchCriteria:mdRecords:4:recContent" style="display: none;"><img id="frmSearchCriteria:mdRecords:4:_imgRecordThumbnail" src="https://landscape.blm.gov/geoportal/thumbnail?uuid=%7BCFFCCB2E-D6D1-4C2D-89C3-A0E7F15F22AC%7D" alt="Metadata Thumbnail" height="64" width="64" class="resultsThumbnail" /><span id="frmSearchCriteria:mdRecords:4:_txtAbstract" class="resultsContent">Cheatgrass climatic habitat under current climate conditions. BEM encompasses. &quot;Bromus tectorum dominated lands in the Great Basin and climatically suitable habitat based on Mahalanobis distance.&quot; (Bradley 2008: Lines 396-397)</span>`

---end row Chrome---

---start row IE---(notice IE does not include the "img" element)

`<td class="metadataCntTypIcon"><span id="frmSearchCriteria:mdRecords:4:recContent" style="display: none;"><span id="frmSearchCriteria:mdRecords:4:_txtAbstract" class="resultsContent">Cheatgrass climatic habitat under current climate conditions. BEM encompasses. &quot;Bromus tectorum dominated lands in the Great Basin and climatically suitable habitat based on Mahalanobis distance.&quot; (Bradley 2008: Lines 396-397)</span>`

---end row IE---

It looks like when Chrome renders it, the row contains the "img" parameters.  IE seems to ignore it. But when you copy/paste the "src" URL in the Chrome output above into the IE browser, you get a dialog prompting you to save it.  IE may be tripping over how it handles "img" elements.  I'm assuming that it's the same response from the server.

Thanks,

Rick

**Comment by rmbradley** [comment]
I think we can close this.  I tried it from a non-work PC by accessing the same resource (it's public facing).  The non-work PC has IE11 and the expanded results displayed the thumbnails with no problem.  I think its a security policy setting for our work-related PCs.  There are some advanced settings in the IE options that have been disabled for non-admin folks.  I will have to track down a System Admin to find out.

**Comment by mhogeweg** [comment]
would be interested in receiving those security settings so we can do some testing on our side.

**Comment by rmbradley** [comment]
Sorry to re-open this issue but an additional symptom has occurred.  I had a colleague test this out with his private PC using IE10.  He could NOT display the thumbnails either.  Also, I was testing this with an account that has administrator permission (on Windows 10 and IE11) with success.  I have not tried with a "normal" account.  I was wondering if you could test it?  Just go to  https://landscape.blm.gov/geoportal, click disclaimer, go to REAs, click on the upper right panel on the REA page and select Downloadable Data link.  This will give you 10 results.  See if you can duplicate the problem.
