### ISSUE TITLE
component GeoportalSearch error in Web AppBuilder for ArcGIS v2.2 Developer Edition

### ISSUE THREAD

**Issue by ebonan** [Esri/geoportal-server#249]
Executing the GeoportalSearch widget in the new Web AppBuilder for ArcGIS v2.2 Developer Edition we receive the following error "NetworkError: 404 Not Found - http://js.arcgis.com/3.18/esri/layers/vector-tile.js".
Is the widget updated for the new api version?

Thank you Enrico

**Comment by ebonan** [comment]
Hi, any news about my last question?
thank you 
Enrico

**Comment by psanyal** [comment]
Hi Enrico,

The fix for this issue is available in develop branch. 

See changeset https://github.com/Esri/geoportal-server/commit/a4d317aff0f888246972d51de88245fc74eb4c41

Thanks,
Pratik
