### ISSUE TITLE
Typos in csw transaction wiki pages

### ISSUE THREAD

**Issue by gcampanile** [Esri/geoportal-server#251]
In the wiki page describing CSW transactions there are some typos: in almost all of the POST examples closing tags are lowercase and do not match with opening tags.
For example: 
/csw:getrecords instead of /csw:GetRecords
/csw:insert instead of /csw:Insert

**Comment by mhogeweg** [comment]
it appears all closing elements are in lowercase. if you look at the source of the page, you should see the source is correct XML. any ideas?

**Comment by gcampanile** [comment]
Sorry I missed to put the page url: 
https://github.com/Esri/geoportal-server/wiki/Catalog-Service
If you mena the browser's source page then mine is coherent with the output, i.e. lowercase closing elements.

**Comment by mhogeweg** [comment]
the wiki source. go to edit mode on the page to see correct XML
