### ISSUE TITLE
GeoPortal server doesn't accept UTF-16 encoded records produced by ArcCatalog

### ISSUE THREAD

**Issue by torrin47** [Esri/geoportal-server#253]
ArcCatalog appears to be producing metadata records that are encoded as utf-16 (Notepad++ reports the encoding as "UCS-2 LE BOM") but GeoPortal server rejects these records as "unable to parse", and will only harvest them if they've been converted to UTF-8.  An example record is attached. Any way to improve the parsing abilities of GeoPortal server, or is this a limitation of the underlying Java libraries? 
[SEGSMetadataRecord.zip](https://github.com/Esri/geoportal-server/files/610285/SEGSMetadataRecord.zip)

**Comment by umacgillivray** [comment]
I haven't run into ArcCatalog outputting utf-16. I do see the issue when we "Upload" your sample metadata using Geoportal, we can fix this. We can also check web accessible folder harvesting.

**Comment by torrin47** [comment]
Based on a call we had in January, we opened a ticket with the desktop metadata team to try to understand why ArcCatalog is outputting UTF-16 - Aleta believes this should be regarded as a bug on the desktop side, so we can probably close this issue on the GeoPortal side.

**Comment by mhogeweg** [comment]
ok. I did have a question out to Aleta, but we'll close this for now
