### ISSUE TITLE
GeoPortal Details page renders Abstract as plain text, ignores HTML

### ISSUE THREAD

**Issue by torrin47** [Esri/geoportal-server#255]
So now ArcCatalog is adding HTML markup to all Abstract/Description fields, regardless of whether or not a metadata author intends to use any markup.  GeoPortal server doesn't seem to have any problem with when harvesting or indexing, but it sure looks unprofessional on the standard details page:
https://edg.epa.gov/metadata/catalog/search/resource/details.page?uuid=%7B75533E17-C91F-4D96-82C2-CB5CC977D78F%7D

`<DIV STYLE="text-align:Left;"><DIV><DIV><P><SPAN>The core mission of Shared Enterprise Geodata and Services (SEGS) is to provide a single point of ownership for geospatial datasets that are national in extent and of general use to all EPA users and to make those datasets available through channels that best meet user needs. SEGS is a core component of the EPA GeoPlatform, supporting the mission of promoting data and service reuse. As most SEGS datasets are resources procured and intended for internal EPA users, this metadata record is intended as an aggregate placeholder helping point users searching EPA's metadata catalog towards these internal resources. The individual metadata records for the datasets themselves are not included in EPA's metadata catalog. Below is a list of available datasets, please see the SEGS home page on the EPA Intranet for additional information and links to distribution points and metadata documents. ACS 5-Year Estimates Block Groups 2007-2011, US Census ACS 5-Year Estimates Counties 2007-2011, US Census ACS 5-Year Estimates Tracts 2007-2011, US Census ACS 5-year Estimates Data 2007-2011, US Census Agriculture, US, 2015, Dun and Bradstreet American Community Survey 2006-2010 Derived Summary Tables for Block Groups American Community Survey 2006-2010 Derived Summary Tables for Counties American Community Survey 2006-2010 Derived Summary Tables for States American Community Survey 2006-2010 Derived Summary Tables for Tracts File Geodatabase American Community Survey 2006-2010 File Geodatabase for Block Groups American Community Survey 2006-2010 File Geodatabase for Counties American Community Survey 2006-2010 File Geodatabase for States American Community Survey 2006-2010 File Geodatabase for Tracts American Indian Reservations, US, 2008, Bureau of Indian Affairs Boundaries Data US, 2015, HSIP Freedom Census Block Boundaries with 2010 Census Population and Housing Unit Counts Educational Institutions, US, 2015, HSIP Freedom Energy, US, 2015, HSIP Freedom Federal Lands, US, 2004, USGS National Map Federal Lands, US, 2004, USGS National Map Golf Courses, US, 2011, NAVTEQ NAVSTREETS Basemap Data, USA, 2015, Navteq NAVSTREETS Boundaries and Places Map Service, US, 2015, Navteq NAVSTREETS File Geodatabase Download Package, North America, 2015, Navteq NAVSTREETS Places of Interest Map Service, US, 2015, Navteq NAVSTREETS Transportation, US, 2015, Navteq National Park Service Boundaries, US, 2014, National Park Service National Register of Historic Places, US, 2014, NPS Neighborhoods, US, 2008, Factle Maps Rural-Urban Designations, US, 2000-2013, USDA-ERS Soil Survey Geographic (SSURGO) Database, US, USDA NRCS StreetMap North America, 2012, Esri US Census 2010 Summary File 1 Derived Population Data File Geodatabase US Census 2010 Summary File 1 File Geodatabase for Block Groups US Census 2010 Summary File 1 File Geodatabase for Blocks US Census 2010 Summary File 1 File Geodatabase for Counties US Census 2010 Summary File 1 File Geodatabase for States US Census 2010 Summary File 1 File Geodatabase for Tracts USA Base Map, 2012, Esri Zipcodes, US, 2015 Q4, HERE (formerly Navteq).</SPAN></P></DIV></DIV></DIV>`

Any recommendations on how we might allow this to be rendered appropriately, since it seems to be imposed on us from the ArcGIS Desktop side of things?

**Comment by umacgillivray** [comment]
We can look at removing the markup from those elements. Actually displaying the markup would be a little more tricky.
