### ISSUE TITLE
ISO 19115 en Geoportal

### ISSUE THREAD

**Issue by oktober1265** [Esri/geoportal-server#264]
Hello,
I have the following query for you
 
I have Geoportal installed and I realize that at the moment of entering metadata under ISO 19115 or ISO 19115-2 this does not bring all the fields that this standard establishes.
 
If you confirm that only a limited number of fields are provided, I would be grateful if you would advise me what I should do to add the rest of the standard or where and how to purchase it to use it.
 
 
Best regards

**Comment by zguo** [comment]
you are right not all the ISO fields are included in the editor, there is a wiki page might be helpful for understanding and customizing the editor, https://github.com/Esri/geoportal-server/wiki/Geoportal-XML-Editor
