### ISSUE TITLE
Sandbox link not working

### ISSUE THREAD

**Issue by kant** [Esri/geoportal-server#267]
On  [geoportal-server/README.md](https://github.com/Esri/geoportal-server/blob/master/README.md) on line:
Want to learn more? Try our [sandbox site](http://gptogc.esri.com/)!
the proposed link is not working.

**Comment by zguo** [comment]
it was updated to use https.

**Comment by rsignell-usgs** [comment]
It seems like https://gptogc.esri.com  is not working again.

**Comment by mhogeweg** [comment]
we had a redirect that was removed. please update your link to: https://gptogc.esri.com/geoportal

**Comment by rsignell-usgs** [comment]
@mhogeweg , thanks!   https://github.com/Esri/geoportal-server/pull/318
