### ISSUE TITLE
CSW request give me just the localhost server adress

### ISSUE THREAD

**Issue by globi84** [Esri/geoportal-server#272]
hi together

i am trying to install a geoportal server. everything works fine.

i have installed java 8, tomcat 8 and geoportal server 1.2.7 on a windows server 2016

when i make a csw request `http://serverName:port/geoportal/csw?Request=GetCapabilities&Service=CSW&Version=2.0.2`

then i get a xml file with few entries. but everywhere stand the just `localhost` not the domain name. of the server

```xml
<ows:HTTP>
<ows:Get xlink:href="http://localhost:8080/geoportal/csw"/>
<ows:Post xlink:href="http://localhost:8080/geoportal/csw">
<ows:Constraint name="PostEncoding">
<ows:Value>XML</ows:Value>
<ows:Value>SOAP</ows:Value>
</ows:Constraint>
</ows:Post>
</ows:HTTP>
```

where can i edit this output.

regards

globi

**Comment by mhogeweg** [comment]
you should not need to set these manually.  are you accessing the CSW GetCapabilities request with a domain name/port? or as localhost? also: is your geoportal behind a (reverse) proxy or such?

**Comment by globi84** [comment]
hi mhogeweg

thanks i could fix it with a proxy and configure at the gpt.xml file the proxy setting
