### ISSUE TITLE
Geoportal 1.2.9 - CSW Harvesting from 1.2.3 Geoportal

### ISSUE THREAD

**Issue by gavincollins** [Esri/geoportal-server#283]
I am attempting to harvest data from a 1.2.3 Geoportal using the CSW method to a new 1.2.9 Geoportal. When I input my url CSW https://www.externalurl/geoportal/csw?Request=GetCapabilities&Version=2.0.2&service=CSW and click the test button Geoportal returns an error message "Unable to connect to the host".

When I input my url into a web browser it loads correctly, Geoportal howver seems to disagree with it.

**Comment by mhogeweg** [comment]
can the server hosting geoportal 1.2.9 'see' the 1.2.3 instance?

**Comment by gavincollins** [comment]
@mhogeweg The 1.2.3 geoportal is accessible externally via the internet, the CSW url I am using loads correctly in a web browser however the Geoportal application seems to not be able to resolve it. Hope that makes sense, please clarify with me however if you have a different diagnostic in mind. Thanks,
Gavin

**Comment by mhogeweg** [comment]
when the test is run, it is run from the server hosting the geoportal. can you share the public 1.2.3 url? I can run a quick test here

**Comment by gavincollins** [comment]
@mhogeweg The two geoportals exist on different servers, it may be difficult for the customer to provide access between the two because they are in different network zones. Emailed you url.

**Comment by gavincollins** [comment]
Issue resolved. Solution was to imported the sites SSL certs into JAVA lib/security/cacerts via cmd prompt.
