### ISSUE TITLE
Can't register REST service endpoint anymore.  Getting HTTP status code {302 - Found} received from server 

### ISSUE THREAD

**Issue by marcgr** [Esri/geoportal-server#287]
I have tried various service endpoints and nothing is registering anymore.  I can test the service link and get a connection successful response, but when I try to create or create and save I get the HTTP status code {302 - Found} received from server and the entry is not added.  I have tried all of the robots.txt drop-down options and that has not helped.  

I tried on the live geoportal test site : https://gptogc.esri.com/geoportal/ and get the same result.

Here is an example endpoint I am trying to register with the ArcGIS protocol:
url: http://lib-arcgis5.library.oregonstate.edu/arcgis/rest/services/land_use_planning/SageGrouseDataViewer/MapServer
soap: http://lib-arcgis5.library.oregonstate.edu/arcgis/rest/services/land_use_planning/SageGrouseDataViewer/MapServer?wsdl

Stumped.

-Marc

**Comment by marcgr** [comment]
Ahem, never mind.  My SOAP url was wrong, needed to remove the /rest/ part.

**Comment by mhogeweg** [comment]
coming back to this, with everyone moving to https connections, I registered the https flavor of the arcgis server and harvested all of the services :-) enjoy!
