### ISSUE TITLE
GitHub project Description field has a bad link to ESRI Geoportal

### ISSUE THREAD

**Issue by threeiem** [Esri/geoportal-server#310]
Currently the link to ESRI Geoportal on the GitHub project's page (near the top) points to **http://gptogc.esri.com/** and returns a 404 (The requested resource is not available). The new link should be...

**http://www.esri.com/software/arcgis/geoportal**

**Comment by mhogeweg** [comment]
thanks. we updated this link (to point to the sandbox site).
