### ISSUE TITLE
Does Geoportal Server support GeoDCAT?

### ISSUE THREAD

**Issue by simongis** [Esri/geoportal-server#317]
We have a large federal organisation looking to use Geoportal Server for their internal metadata solution.  A key requirement is to support making the catalog available as GeoDCAT.

Is this something that Geoportal Server offers by default, or perhaps something that someone has some experience with?

**Comment by mhogeweg** [comment]
hi Simon, are they interested in using Geoportal 1.x or 2.x?

**Comment by simongis** [comment]
Which ever one ticks the majority of their requirements.  
Forgive me - fairly new area for me.  
I know with an ArcGIS Open Data site, it provides a DCAT endpoint so that other portals can harvest data from it.  From what I read, GeoDCAT looks like it is more focused on describing metadata about spatial datasets.

So this agency are wanting to know if Geoportal Server can output a catalog using this GeoDCAT endpoint?

**Comment by mhogeweg** [comment]
We will need to do work and that will take some time as we have limited resources.

We have implemented the US DCAT profile as used in data.gov. This is also what is in the Hub. 

GeoDCAT-AP is much more elaborate and centered on linked data formats (like RDF/XML, turtle, n3)


I’ll check with the developers a bit more

**Comment by simongis** [comment]
Thanks.  Im happy to close the issue off for now.  Consider it a mild enhancement from our side for you guys to consider.  For now, we can put 'do not comply'

Further down the line, if it comes up as a pressing requirement, we could perhaps assist in contributing the capability into back into the repo.  Easier said than done, but can assess later down the line.

Thanks for the quick responses!
