### ISSUE TITLE
Geoportal Installation on Window server 2019

### ISSUE THREAD

**Issue by FolusoA1** [Esri/geoportal-server#323]
Can Geoportal latest version run on Window server 2019?

**Comment by mhogeweg** [comment]
While this environment is not tested, as long as you can run Java, a container like Apache Tomcat, and a RDBMS you should be fine.

**Comment by FolusoA1** [comment]
Thank you !

**Comment by mhogeweg** [comment]
Please let us know how this goes or if you have issues getting Geoportal Server running on Windows 2019.
