### ISSUE TITLE
Publishing files from ArcGIS Online to Geoportal

### ISSUE THREAD

**Issue by Durga07** [Esri/geoportal-server#328]
Hi, Can I publish the files from my ArcGIS Online account to the Geoportal Catalog without using Harvester??
If yes, can you refer the process to me?

Thank you,
Durga

**Comment by mhogeweg** [comment]
hi, no. Geoportal works with metadata only. the item description in ArcGIS Online can be considered metadata so you could setup your geoportal to index that. Geoportal Server does not host data or files or apps. those will need to be kept elsewhere such as in ArcGIS Online.

**Comment by syntaxdeveloper** [comment]
Hi @mhogeweg,

For hosting data can you let us know the opensource options which work with Geoportal?

**Comment by mhogeweg** [comment]
if you're hosting files then IIS or Apache HTTPD work. But I'm confused, you have an ArcGIS Online subscription.
