### ISSUE TITLE
Search Box

### ISSUE THREAD

**Issue by Durga07** [Esri/geoportal-server#330]
Hi,

I went through the Lucene Search Text Queries(Lucene Search Syntax) in which it is mentioned that we should use double quotes ("world imagery") to get the search result containing those words directly after each other. Is there any other way to get the search result as most relevant without using the syntax (i.e., the double quotes or fields) given. For example, if we search just the phrase _World imagery_ we should get the data containing those two words directly next to each other.

**Comment by mhogeweg** [comment]
you would have to assume that this is the behavior wanted whenever two terms are included. once done you can programmatically add the quotes after the user hits the Search button. Please note that we have moved on to Geoportal 2.x development. Please consider switching to https://github.com/Esri/geoportal-server-catalog

**Comment by Durga07** [comment]
Hi,

We are using the 2.6.3 version of Geoportal. Can you please specify where can I change the program code to make the search more optimized without using double quotes.

**Comment by mhogeweg** [comment]
Please move this discussion to the 2.x github repo:
https://github.com/Esri/geoportal-server-catalog/issues

This repo here is for 1.x only
