### ISSUE TITLE
Connect Geoportal with ArcGIS Experience Builder

### ISSUE THREAD

**Issue by kgauravm30** [Esri/geoportal-server#334]
Hi All,

Is there any geoportal widget for ArcGIS Experience Builder.

**Comment by zguo** [comment]
Currently we don't have a geoportal widget for ArcGIS Experience Builder yet, most likely will be in the future.

**Comment by mhogeweg** [comment]
on approach is to use the geoportal search component in combination with an embed widget in Experience Builder.

![image](https://user-images.githubusercontent.com/394890/102946246-edb6b000-4474-11eb-8fb8-6bc7894d561c.png)

**Comment by kgauravm30** [comment]
Hi,
I hope you are doing well.

The embed widget option is not working for my requirement in Experience Builder. I need to integrate an ESRI geoportal search in existing Experience builder app.

Can we get search widget code if any for Experience builder either that code is completed or in development 
phase.

Regards
Gaurav
