### ISSUE TITLE
Enhancement: uploading/harvesting in draft

### ISSUE THREAD

**Issue by gcampanile** [Esri/geoportal-server#76]
Whene uploading or harvesting a record, if this does not passes validation it should be possibile to uploaded in draft status. Sometimes harvesting discards many records which could be inserted in draft mode and modified at later time with the edito; in our experience this enhancement could save a lot of time and effort.

Suggestion for this enhancement:
1. In the upload page a flag should indicate wether to save the document as a draft if not validated
2. In the external resource registration page a flag should be added (and so in the DB) to specify if record from the remote catalogue should be added in draft when not validated

Any comment/question is appreciated.

Gianni

**Comment by zguo** [comment]
duplicate with #181.

**Comment by pandzel** [comment]
Closed with #181
