### ISSUE TITLE
Complete Metadata of a service not available with Geoportal

### ISSUE THREAD

**Issue by denishr** [Esri/geoportal-server#91]
Using ArcCatalog, I tried creating the metadata of an ArcGIS Server service with the ISO 19139 / 19119 standard. But while registering this service with geoportal, only the basic metadata information of the service (such as title, description and tags) are getting saved to geoportal database. How can I access the additional metadata information (such as owner, contact details etc of the service)? For this, do I miss anything while registering the service with geoportal?

**Comment by mmorcal** [comment]
I have the same problem. I have edited the metadata (ISO 19139) of my map document (mxd) in ArcCatalog. Then I have published the map service and I can view metadata information if I go to:

http://myServer:6080/arcgis/rest/services/TestService/MapServer/info/metadata

When I register my server in Geoportal, I only view the basic metadata information of the service.

If I export the xml of my map service and then I register it with Geoportal, I can view and search all metadata.

Can you resolve your problem?

**Comment by mhogeweg** [comment]
this ability is on our roadmap. until then the export and upload path is the way to go.
