### ISSUE TITLE
symbol for points data in the REST kml

### ISSUE THREAD

**Issue by Yuanjie0913** [Esri/geoportal-server#95]
We found the REST API kml is very useful in displaying data spatially with links. But there is no clear symbol for point data. Please see this link https://maps.google.com/maps?q=http:%2F%2Fdata.nodc.noaa.gov%2Fgeoportal%2Frest%2Ffind%2Fdocument%3FsearchText%3D%2522moorings%2522%2520AND%2520%2522Pacific%2520Marine%2520Environmental%2520Laboratory%2522%2520AND%2520%2522CO2%2522%26start%3D1%26max%3D30%26contentOption%3Dintersecting%26spatialRel%3DesriSpatialRelOverlaps%26bbox%3D-180%252C-90%252C180%252C90%26f%3Dkml&hl=en&sll=38.804821,-77.236966&sspn=3.159017,5.674438&t=m&z=3

How to modify the data symbols shown in the kml?

Thanks,
Li

**Comment by pandzel** [comment]
That would require to understand KML mechanisms how to achieve that. With enough information you could possibly modify KmlFeedWriter.java class and rebuild geoportal. There is no configuration settings to do that without rebuilding the project.
