### ISSUE TITLE
A question about Geoportal's indexing process

### ISSUE THREAD

**Issue by Yuanjie0913** [Esri/geoportal-server#96]
Hi Marten,
This is not an issue, but something we would like to know. How does geoportal builds up its Lucene index? We have experienced few times when our geoportal was doing indexing, then suddenly the system gives error 'Exception in thread "Lucene Merge Thread #1" org.apache.lucene.index.MergePolicy$MergeException: java.io.IOException: No space left on device'; this breaks geoportal, but another internal process manages to remove its temporary files, reducing disk utilization back to where it was before the process started. 

Any advice is appreciated!

Li

**Comment by zguo** [comment]
it is suggested to keep the available disk space at least 3x of index size to work properly.
